- README.md
- playbooks/gitea.yml
- playbooks/hygieia.yml
- playbooks/post.yml
- provision.sh
- vars/mdt.yml
Changes to application and Jenkins deployment
Dependent on https://github.com/redhat-cop/container-pipelines/pull/58
> Enhancements to support Jenkins pipeline and sample application

- metrics-exporters/leadtime-exporter/Dockerfile
- metrics-exporters/leadtime-exporter/app.py
- metrics-exporters/leadtime-exporter/lt-exporter.py
- metrics-exporters/leadtime-exporter/requirements.txt
@etsauer 
I created the required exporter, I tested locally using podman with UBI image as well, the template you created earlier should match except for a needed ~/.kube/config file
The exporter is expecting 3 Enivronment Variables:
GITHUB_USER: mandatory
GITHUB_TOKEN: mandatory 
PROJECTS : list of comma separated project names, This is optional, and if not set, the exporter will fetch all the user projects
The exporter relies on ~/.kube/config file to connect to openshift clusters, the file should be mounted to the pod .
> Lead Time Exporter

- README.md
- charts/deploy/.helmignore
- charts/deploy/Chart.yaml
- charts/deploy/charts/namespaces/.helmignore
- charts/deploy/charts/namespaces/Chart.yaml
- charts/deploy/charts/namespaces/templates/ns.yaml
- charts/deploy/charts/namespaces/values.yaml
- charts/deploy/templates/_helpers.tpl
- charts/deploy/templates/dashboard-sdm.yml
- charts/deploy/templates/grafana-mdt-datasource-secret.yaml
- charts/deploy/templates/prometheus-cr.yaml
- charts/deploy/templates/prometheus-htpasswd-secret.yaml
- charts/deploy/templates/prometheus-oauth-clusterrole.yaml
- charts/deploy/templates/prometheus-oauth-clusterrolebinding.yaml
- charts/deploy/templates/prometheus-operator-rbac.yaml
- charts/deploy/templates/prometheus-operator-sa.yaml
- charts/deploy/templates/prometheus-operator-service.yaml
- charts/deploy/templates/prometheus-operator.yaml
- charts/deploy/templates/prometheus-route.yaml
- charts/deploy/templates/prometheus-sa.yaml
- charts/deploy/templates/prometheus-scrape-config-secret.yaml
- charts/deploy/templates/prometheus-service.yaml
- charts/deploy/values.yaml
> WIP: Initial helm-based deployment

- .gitignore
- README.md
- charts/deploy/charts/namespaces/templates/ns.yaml
- exporters/deploytime/README.md
- runhelm.sh
To Test:
Follow main README to install using the `-n` flag
> Allow pelorus to be installed in any namespace

- charts/deploy/templates/metrics-dashboard.yaml
- charts/deploy/templates/prometheus-rules.yaml
Modify Change Failure Rate to use MTTR (failure exporter) metrics.
resolves #57
> Implement CFR using MTTR metrics

- runhelm.sh
The '-d' flag for base64 is a debugging flag on Mac.  Need to use '-D' instead.  [link](https://electrictoolbox.com/base64-decode-command-line/)
> Update Helm Script with Mac Conditional

- charts/deploy/templates/prometheus-cr.yaml
- charts/deploy/templates/prometheus-operator.yaml
Lowering request for prometheus and operator pods
> Lowering request for prometheus and operator pods

- exporters/committime/app.py
- exporters/lib_pelorus/loader.py
> Implement a logging framework and better exception handling

- docs/Install.md
- runhelm.sh
> Temporary fix for passing helm args

- exporters/committime/app.py
- exporters/lib_pelorus/loader.py
This should resolve the final linting error as well.
> Refactor main committime method to reduce complexity

- README.md
Add the Pylama pass/failure badge.
> Add Pylama status badge

- exporters/committime/app.py
Add a cache, so we don't query the API over and over again for the same commit.
To test: 
1. Deploy pelorus
2. Change log level to debug
3. Run committime exporter and look for log lines that specify if commit_time is pulled from cache or API
resolves #66
> Implement Git commit_timestamp cache

- exporters/pelorus.py
> Add default datefmt and format to logger

- charts/deploy/Chart.yaml
- charts/deploy/templates/metrics-dashboard.yaml
@redhat-cop/mdt 
resolves #119
> Update queries to more accurately measure DF and CFR over time

- .github/workflows/conftest.yaml
- .gitignore
- _test/TESTING.md
- _test/bats-support-clone.bash
- _test/conftest.sh
Addes conftest action and tests. 
resolves https://github.com/redhat-cop/pelorus/issues/148
See action or `bats _test/conftest.sh`
> Added conftest tests to resources

- .github/workflows/conftest.yaml
- .github/workflows/unittests.yml
- docs/Development.md
- exporters/requirements-dev.txt
- exporters/requirements.txt
- exporters/test_pelorus.py
> Start a unittest suite

- exporters/committime/app.py
- exporters/committime/collector_bitbucket.py
- exporters/pelorus.py
- tests/test_pelorus.py
resolves #106 
resolves #188 
Fully testing the PR requires the cloud and on-prem versions of Bitbucket.  I have a sample [repo on bitbucket.org](https://bitbucket.org/themoosman/logs-a-lot/src/master/) that can be used for testing the cloud version.  For the on-prem version, BB can be run in a [container](https://hub.docker.com/r/atlassian/bitbucket-server/). 
> Issue 106 - Bitbucket Integration

- docs/Configuration.md
Documentation fix.
resolves #199 
No tests needed
> Fix reference to helm chart in Configuration.md

- docs/Development.md
> Add release process to developer docs

- labs/consultant/02-Installation.md
> Fix whitespace

- labs/consultant/02-Installation.md
fix some typos from the exercise...
@etsauer 
> 🦄 FIX - typos and tweaks for ex 1 🔥

- labs/consultant/03-Exporters.md
> Fix Jira URL token

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/dashboard-sdp.yaml
Deploy pelorus stack, and review the changes made to the Software Delivery Performance global dashboard.
> Add an overall software delivery score to the global dashboard

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/dashboard-snapshot-cronjob.yaml
Fix Grafana malformed snapshots
resolves #https://github.com/redhat-cop/pelorus/issues/238
> Fix Grafana malformed snapshots

- labs/consultant/02-Installation.md
- labs/consultant/03-Exporters.md
Clarify & fix labs consultant docs, some missing steps.
> Clarify consultant lab docs

- docs/index.md
Prior knowledge assumptions note.
resolves #https://github.com/redhat-cop/pelorus/issues/117
> Prior knowledge assumptions note

- docs/Configuration.md
- docs/Demo.md
- docs/Install.md
> Some minor suggestions to the documentation

- .github/workflows/build-pelorus.yaml
quick fix
Action documentation is [here](https://github.com/marketplace/actions/push-to-registry)
> updated gh action push-to-registry to v2, modified spec to match

- .github/workflows/build-pelorus.yaml
> 'tag' key -> 'tags'

- .github/workflows/build-pelorus.yaml
Removed latest tag from push event, added step to workflow for retagging every image as latest
> Fix image retag

- .github/workflows/build-pelorus.yaml
- .github/workflows/release.yaml
Happens to the best of us sometimes ...
> correct names for github actions secrets

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/dashboard-sdp-byapp.yaml
resolves #274 
1. Deploy Pelorus, and wire up the failure exporter to either Jira or ServiceNow
2. Generate some failure data, and lead time data
3. Make sure that the "By App" dashboard shows data in all graphs.
> Failure over time dashboard fix

- docs/Install.md
Also fix formatting around installation steps
`mkdocs serve`
> Clarify repo requirements in the docs

- docs/Install.md
> Add git to list of prereqs

- .github/workflows/chart-lint.yml
- .github/workflows/conftest.yaml
- .github/workflows/prometheus-rules.yml
- .github/workflows/python-formatting.yml
- .github/workflows/python-linting.yml
- .github/workflows/unittests.yml
Makes PR checks only trigger if their relevant paths are modified.
> Make PR checks more selective based on paths

- .github/workflows/build-pelorus.yaml
Temporary workaround due to podman changes
https://github.com/redhat-actions/push-to-registry/issues/42#issuecomment-882583602
> Use ubuntu-18.04 for build-pelorus

- .github/workflows/chart-lint.yml
- .gitignore
- chart_schema.yaml
- charts/pelorus/Chart.yaml
This is just https://github.com/konveyor/pelorus/pull/324 from my fork.
I'm getting a protected branch error that seems nonsensical.
```
remote: error: GH006: Protected branch update failed for refs/heads/update_chart_linting.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/konveyor/pelorus.git
! [remote rejected] update_chart_linting -> update_chart_linting (protected branch hook declined)
error: failed to push some refs to 'https://github.com/konveyor/pelorus.git'
```
> Update chart linting

- docs/Development.md
- labs/consultant/03-Exporters.md
Updates the docs for the release management process to reflect the new stable tagging method.
Depends on #325 but can be rebased so it doesn't.
related to #303
related to #316
> Docs version change for v1.4.0 rc

- docs/Dashboards.md
- docs/DemoTroubleshoot.md
- docs/Development.md
- docs/Install.md
- docs/Philosophy.md
resolves #334 <-- Use this if merging should auto-close an issue
> Fixed links in documentation (#334)

- Makefile
> Define maximum python version in Makefile

- OWNERS
- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
OWNERS file required by OpenShift workflows
This file is needed for the OpenShift workflow apps to understand who can merge or review code by commenting on the PR.
> OWNERS file required by OpenShift workflows

- samples/README.md
> sample needs webhook secret and proper app path

- exporters/committime/app.py
- exporters/deploytime/app.py
- exporters/pelorus/__init__.py
- exporters/pelorus/utils.py
- exporters/requirements.txt
Fixes Issue #262, which uses newer version of OpenShift python module.
related to #446 
> Use new python openshift version 0.13.1

- scripts/run-pelorus-e2e-tests
* allow the user of the script to update git commits AND
github issues in their fork of mig-demo-apps
how to test:
* fork mig-demo-apps, enable github issues
./scripts/run-pelorus-e2e-tests -e failure -o weshayutin
* create an issue w/ proper labels, close an issue
> allow the github issue org to updated to optional org

- exporters/deploytime/app.py
> ensure deploytime timestamp is set to the deploytime

- docs/Configuration.md
> Improve failure time exporter documentation

- exporters/committime/collector_base.py
Fix for Issue #514
With fix:
```
06-22-2022 14:48:20 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/collector_base.py:193 get_metrics_from_apps() Adding metric for app python-binary-build1
06-22-2022 14:48:20 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/collector_base.py:182 get_metrics_from_apps() Repo URL for app python-binary-build11 is currently None
06-22-2022 14:48:20 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/__init__.py:100 __parse_repourl() repo url = None
06-22-2022 14:48:20 WARNING  Missing data for CommitTime metric from Build first/python-binary-build11-1 in app python-binary-build11: Couldn't get repo_url.Couldn't get commit hash from annotations
```
Without …
> Fix the traceback if no commit sha is found

- README.md
- docs/UpstreamSupport.md
> craft an upstream support policy

- Makefile
> test the failure exporter by default via the makefile

- .github/workflows/shellcheck.yaml
- Makefile
- demo/demo-tekton
- scripts/run-pelorus-e2e-tests
> Add shellcheck github workflow

- Makefile
- docs/Development.md
- scripts/bump-version
Changes to the Development documentation to reflect current implementation.
Small change to the bump-version to make it work (tested on python 3.10.4).
Also Fixes #305
> Improve developer documentation

- exporters/failure/collector_github.py
> fix problem with various bug labels in github

- charts/pelorus/Chart.yaml
- charts/pelorus/configmaps/committime.yaml
- charts/pelorus/configmaps/failuretime.yaml
- charts/pelorus/secrets/github_example.yaml
- charts/pelorus/secrets/jira_example.yaml
- docs/Configuration.md
- docs/Development.md
- docs/Install.md
- exporters/committime/app.py
- exporters/failure/app.py
- exporters/failure/collector_jira.py
- exporters/failure/collector_servicenow.py
- exporters/pelorus/__init__.py
- exporters/tests/test_pelorus.py
- labs/consultant/03-Exporters.md
- mocks/README.md
- samples/todolist_commit_deploy.md
> Use API_USER instead of USER

- docs/UpstreamSupport.md
- mkdocs.yml
Issue: https://github.com/konveyor/pelorus/issues/285
resolves #285 
> supported exporters and status of each

- demo/demo-tekton.sh
- demo/python-example/Dockerfile
- demo/tekton-demo-setup/02-project.yaml
- demo/tekton-demo-setup/03-build-and-deploy.yaml
Switch to Universal Base Images
Move task to pipeline setup, namespace it
Clarify documentation
Make demo template formatting nicer
---
I had trouble getting #587 working for me. This should fix that. WIP until I have some more clarification on things from #587.
> Clean up tekton demo

- docs/Configuration.md
JIRA defult and custom workflows explained.
Resolves #550
Testing: https://pelorus--607.org.readthedocs.build/en/607/Configuration/#failure-time-exporter
> JIRA configuration examples

- demo/demo-tekton.sh
- demo/tekton-demo-setup/02-project.yaml
- demo/tekton-demo-setup/03-build-and-deploy.yaml
FYI.. this requires an rbac update to label the image
e.g. https://github.com/kubevirt/kubevirt-tekton-tasks/blob/main/docs/tasks-rbac-permissions.md
> label and annotate s2i tekton build

- docs/Configuration.md
- docs/Noobaa.md
Nit to include namespace in the noobaa CLI commands, plus small example of the Pelorus config.
Additionally fixes minor nit where href tag was wrong.
> Small doc update for noobaa to include namespace

- README.md
Add a link to code of conduct in the readme page
> Add a link to CoC in readme

- demo/python-example/response.txt
This reverts commit 0de34cad4bc6f5d69d56cd93171eadde1b673137.
> Revert "modifying python example, number 1"

- .github/workflows/python-linting.yml
- Makefile
- exporters/requirements-dev.txt
- pylava.ini
- pyproject.toml
This takes out some bits from #615 which are not really related to #549.
Author: Kevin M Granger <kgranger@redhat.com>
> Use pylama for python linting

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- docs/Install.md
Small patch release before our MVR to test containers.
> Pre-mvr release (1.8.1)

- exporters/committime/collector_base.py
- exporters/failure/collector_base.py
Reverts konveyor/pelorus#513
resolves #650 
resolves #651
> Revert "Report resource timestamp as metric timestamp"

- scripts/view-grafana-queries.py
Related to debugging #650 and #651
> Add script to view all grafana queries in the SDP dashboard

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- docs/Install.md
Small patch release before our MVR to test containers.
> Pre-mvr release (1.8.2)

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- docs/Install.md
Minimum Viable Release of the Pelorus project.
> major release of the Pelorus project - MVR 🎉

- .git-blame-ignore-revs
While the original commit was added, the merge commit never was.
Signed-off-by: Kevin M Granger <kgranger@redhat.com>
> Fix git blame ignore file

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- docs/Install.md
With the PR #680 that resolved #678 we need to create new patch version that contains the hotfix.
> New hotfix release to cover fix for the bitbucket API 1.0

- exporters/pelorus/config/__init__.py
- exporters/tests/integration/test_bitbucket.py
- exporters/tests/integration/test_committime.py
- exporters/tests/openshift_mocks.py
- exporters/tests/test_deploytime.py
- exporters/tests/test_exporters.py
- scripts/troubleshooting/missing_labels.py
Appease type checker a bit for further work on #708 / #710.
We could add this to #710 if we wish.
> Appease type checker, make some test setup more correct, fix troubleshooting script

- docs/GettingStarted/configuration/PelorusCore.md
https://pelorus--779.org.readthedocs.build/en/779/
> New Pelorus Core config doc

- demo/README.md
- docs/GettingStarted/QuickstartTutorial.md
* general cleanup
* use sed to edit pelorus instance yaml
* include documentation links to secrets
* include steps to exerise the failure exporter
> Updates to tekton demo instructions as requested by Mateus

- .github/workflows/chart-lint.yml
- .github/workflows/integration-tests.yml
- .github/workflows/mockoon-tests.yml
- .github/workflows/python-formatting.yml
- .github/workflows/python-linting.yml
- .github/workflows/shellcheck.yaml
- .github/workflows/typecheck.yml
- .github/workflows/unittests.yml
- docs/Development.md
- scripts/python-version-check.py
checked the following:
* unit tests
* integration tests
* lint
seems to work :)
> bump python version check to 3.11

- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- scripts/pelorus-operator-patches/bundle-patches/01_prometheus_grafana_dependencies.diff
We need to adjust our CSV to include replaces/skips.
> Update of deps to the operator 0.0.2

- docs/GettingStarted/configuration/ExporterFailure.md
This updates the configuration options sections and it's descriptions to the layout/format that is used in other parts of the documentation.
> Small format update to the exporter failure doc

- docs/GettingStarted/Installation.md
- docs/GettingStarted/configuration/ProductionBestPractice.md
- docs/index.md
- mkdocs.yml
- overrides/home.html
Update the the Documentation Home page (index.md file).
No.
Check the read the docs CI job to see the documentation changes introduced in this PR.
**NOTE: Just review/merge this PR after we finish the other documentation PRs.**
> fix: Update documentation home page (index) and docs menu

- OWNERS
As per discussion pool in #805 adding
mateusoliveira43 as the REVIEWER/APPROVER.
> Update OWNERS file to address #805

- charts/configmaps/committime.yaml
- charts/configmaps/deploytime.yaml
- charts/configmaps/failuretime.yaml
- charts/configmaps/pelorus.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/subcharts/exporters/Chart.yaml
- charts/pelorus/subcharts/exporters/templates/default_configmaps.yaml
- charts/secrets/github_example.yaml
- charts/secrets/jira_example.yaml
- exporters/pelorus/certificates.py
Fix broken links. I used `grep -Iinr 'https://pelorus.readthedocs.io' .` to help me.
resolves https://github.com/konveyor/pelorus/issues/801
Check if the links are correct now.
> fix: Charts links

- .github/workflows/release.yml
Wrong number of spaces in one of the actions.
> Follow up fix for pr #859 - fix indentation for github action

- docs/GettingStarted/configuration/ExporterDeploytime.md
- docs/GettingStarted/configuration/PelorusExporters.md
- exporters/tests/test_webhook_models.py
- exporters/webhook/models/pelorus_webhook.py
General small fixes in the source code of the project.
resolves #867
resolves #897
related to #894
Check new test to avoid application breaking with wrong payload is sent to webhook.
Check preview documentation of readthedocs job: https://pelorus--901.org.readthedocs.build/en/901/
> fix: Small general fixes

- scripts/run-pelorus-e2e-tests.sh
Enables webhook exporter with and without secret
in our e2e tests.
Fixes #858
Depends on: https://github.com/konveyor/mig-demo-apps/pull/101
Test command examples:
```
$ ./scripts/run-pelorus-e2e-tests.sh -e webhook,webhook_with_secret
$ ./scripts/run-pelorus-e2e-tests.sh -e webhook
$ ./scripts/run-pelorus-e2e-tests.sh -e webhook_with_secret
```
> Enhance e2e script test to cover webhook exporter

- .github/workflows/chart-lint.yml
- .pre-commit-config.yaml
- exporters/setup.py
- scripts/chart-test.sh
resolves #966
Exporters version (quay tag) should be updated every time exporters folder is modified.
Test different scenarios, like just updating exporters folder, just updating charts folder, just updating pelorus-operator folder, and checking if the script catches all wrong usages.
> fix: Version validation for exporters

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- scripts/chart-test.sh
- scripts/create_release_pr.sh
resolves #966
Check also the versions in other files of charts folders.
Try not updating the versions in `charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml` or `charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml` and check if `make chart-lint` warns you.
> fix: Add constrain to make chart-lint

- .github/workflows/test-images.yml
related to #881
Fix wrong command in job.
Check following PR.
> fix: New test image job

- .github/workflow_templates/comment-pr/Dockerfile
related to #881
Fix path inside Dockerfile.
Check following PR.
> fix: Custom action dockerfile

- .github/workflows/test-images.yml
- .github/workflows/trigger-test-images.yml
related to #881
Test if new job is working as expected.
Check CI logs and comments in this PR.
> test: Test new job

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/ci.yml
- Makefile
- README.md
- docs/UpstreamSupport.md
- scripts/check_openshift_version.py
resolves #928
related to https://github.com/openshift/release/pull/39650 (the CI job should fail until this PR is merged)
Create a check for the OpenShift versions the project uses.
Check CI logs and run the new script with `make openshift-check-versions`.
> fix: Update OpenShift versions

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- docs/Development.md
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
related to #1050
Release for version 0.0.8 of Pelorus Operator.
To test the release candidate, run the command the CI posted in this PR.
Also, read, review and update [release body](https://github.com/dora-metrics/pelorus/releases) marked as drafted.
> release: Pelorus Operator version 0.0.8

- .github/workflows/cd.yml
- .github/workflows/test-images.yml
Modification to ensure VERSION is taken properly.
> Modify workflow to ensure VERSION is correct

- .github/workflows/cd.yml
related to https://github.com/dora-metrics/pelorus/issues/1008
Change fork user to run CD with new release.
Check that token works with fork user.
> fix: fork user

- docs/Development.md
- scripts/chart-test.sh
related to https://github.com/dora-metrics/pelorus/pull/1131
Fix missing parts (`grep -Inr '"VERSION ?= "' .`) from related PR.
Check that all places have been updated.
> fix: grep version

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- docs/Development.md
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
related to #1134
Release for version 0.0.9 of Pelorus Operator.
To create this PR, https://pelorus.readthedocs.io/en/latest/Development/#create-a-release was followed and run `./scripts/update_projects_version.py -f -l patch patch`
To test the release candidate, run the command the CI posted in this PR.
Also, read, review and update [release body](https://github.com/dora-metrics/pelorus/releases) marked as drafted.
> release: Pelorus Operator version 0.0.9

- .gitignore
- devfile.yaml
- pelorus.code-workspace
I've started using Dev Spaces as my main development environment instead of my local machine. I'd like to contribute the devfile I'm using for pelorus development.
Open an instance of OpenShift Dev Spaces or Eclipse Che, and create a workspace from this branch, using the URL `https://github.com/etsauer/pelorus/tree/devspaces-workspace`
> Create a workspace for use with Eclipse Che/OpenShift Dev Spaces

- OWNERS
> Update OWNERS - add cgruver

- .github/workflows/test-images.yml
related to #1159 
depends on #
Need to fix CI before #1159 would pass
> Change name of exporter deployment file ahead of a refactor

- .github/workflows/conftest.yml
- _test/conftest.sh
- _test/test_prometheusrules.sh
> fix directory references for charts dir that was moved

- .github/workflows/cd.yml
- .github/workflows/conftest.yml
- .github/workflows/trigger-test-images.yml
- _test/conftest.sh
- _test/test_prometheusrules.sh
> Fix conftest and prometheus_rules tests and see if we can get test bundle to build off of main

- .github/workflows/test-images.yml
> Adjust conditional to trigger a PR comment after operator build
