- README.md
- provision.sh
Will cleanup a typo in README and also have the README match the input of provision.sh, was expecting -n in script, said -h on the README
> Cleanup README and Provision Script

- metrics-exporters/commit-time-exporter/Dockerfile
- metrics-exporters/commit-time-exporter/commits-exporter.py
- metrics-exporters/commit-time-exporter/requirements.txt
This is a sample metrics that pulls commit time and export so Prometheus can be configured to pull the data from /metrics.
The data will have labels for commit hash and repository name.
The application is expecting 3 environment variables:
- GITHUB_USER: Github User name
- GITHUB_TOKEN: Github API token
- GITHUB_REPOS: comma separated list of repositories
Example to run the app:
```
oc new-app https://github.com/AlyIbrahim/mdt-quickstart.git#metrics-exporters --context-dir=metrics-exporters/commit-time-exporter --name=commits -e GITHUB_USER=$GITHUB_USER -e GITHUB_TOKEN=$GITHUB_TOKEN -e GITHUB_REPOS="redhat-cop/mdt-quickstart, AlyIbrahim/bitbucket-client" --name commit-exporter
oc expose svc commit-exporter
```
@etsauer
> Add: GitHub Commit Time Exporter

- exporters/committime/app.py
The issue wasn't due to the non-GitHub repo.  The code wraps the line `self.commit_time = commit['commit']['committer']['date']` in a try/catch.  So if the repo is non-GitHub the catch is triggered.  However, the next line tries to reference `self.commit_time` and the null pointer is thrown.  So, I moved both lines in the try/catch since they're related.  
resolves #59
> Fix for Issue #59

- charts/deploy/templates/grafana-thanos-datasource.yaml
- charts/deploy/templates/thanos-objstore-config-secret.yml
- charts/deploy/templates/thanos-store-cert-configmap.yml
- charts/deploy/templates/thanos-store.yml
- docs/Install.md
- docs/Storage.md
- storage/minio-scc.yaml
Pull request for someone to test the steps for installing long term storage. I did overwrite our installation instructions to assume that people will be using minio.
Future work will provide options to change the bucket types to S3, GCS, etc
> Long term storage for #23 [WIP]

- charts/deploy/templates/grafana-thanos-datasource.yaml
If `bucket_access_point` isn't specified, then Pelorus defaults to no LTS and uses the legacy Prometheus service endpoint.  
resolves: #89
> Fix for issue #89

- exporters/committime/app.py
- exporters/deploytime/app.py
- exporters/failure/app.py
- exporters/lib_pelorus/loader.py
> Fix issue 88; resolve linting errors in exporters

- charts/deploy/templates/cluster-ca-bundle-configmap.yaml
- charts/deploy/templates/grafana.yaml
- charts/deploy/templates/prometheus-cr.yaml
- charts/deploy/values.yaml
- docs/Configuration.md
- docs/Install.md
This PR supports configuring Pelorus to use a custom CA.
This can be tested on a cluster with a privately signed wildcard certificate by setting `custom_ca: true` in the values.yaml for the deploy chart. (see new `/docs/Configuration.md` for specifics). 
resolve #91
> Support custom ca

- exporters/deploytime/app.py
Found an issue where `ReplicationControllers`  that contain unresolved image references are missing a SHA256 component in the URL cause a `NoneType` exception that crashes the exporter. This PR handles that exception.
> Fix issue with unresolved image reference

- docs/Configuration.md
- exporters/deploytime/app.py
- exporters/pelorus.py
This PR add the ability for an admin to set a label, such as `env=production` as the search criteria for namespaces in scope for tracking deployment metrics.
To Test:
1. Spin up deploytime exporter locally. Behavior should be same as before.
2. Set `PROD_LABEL="env=production"` and spin up exporter again. Initially you should see no metrics captured. 
3. Label a relevant namespace like `oc label ns/basic-nginx-prod env=production`, and then `curl localhost:8080` to trigger again, and you should see metrics from that namespace.
> Add production label to deploytime metric

- charts/deploy/templates/grafana.yaml
- charts/deploy/templates/prometheus-cr.yaml
- charts/deploy/templates/thanos-query.yml
This PR does the following
* adds support for custom CAs in the thanos component (we missed this when we resolved #91 )
* resolves #105
To test:
1. Deploy pelorus with and without thanos. Make sure that the dashboard is working.
2. Configure a custom wildcard cert, and ensure you can still log into thanos.
> Resolve several outstanding issues with thanos component

- .github/pull_request_template.md
- docs/Development.md
@redhat-cop/mdt 
resolves #109
> Add some testing guidance and a PR template with a reference to it.

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/rbac.yaml
#170 called out a bug where we didn't properly clean up a static reference to the `pelorus-exporter` clusterrole after we renamed the role to `pelorus-exporter-{{ .Release.Namespace }}`. We didn't catch it because we are testing in "dirty clusters" where the role still exists.
resolves #170 
1. Make sure that you clean out any previously applied role with `oc delete clusterrole pelorus-exporter`.
2. Follow install doc.
> Fix rolebinding reference for exporter role

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/rbac.yaml
- exporters/deploytime/app.py
This will process ReplicaSets which are used for deployment type configurations.
resolves #165 
Run the deploytime exporter and verify values for ReplicaSets which are related to Deployment configurations.
> Process ReplicaSets

- exporters/test_exporters.py
A previous PR resulted in a test file getting wiped out of the repo. I'm adding it back.
https://github.com/redhat-cop/pelorus/blob/367cadd746e3c227f9698c11b4e934dd071beef0/exporters/test_pelorus.py
> Re-add tests that were removed in a previous PR

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/tests/pelorus-grafana-test-job.yaml
This PR adds a helm test hook in the form of a k8s job.
This job checks all the Prometheus targets are "UP".
To run the test once Pelorus has been deployed succesfully:
helm test pelorus
If this get merged, I would like to reactor testing documentation with this update, as it seems a bit disperse/hidden in the repo.
A couple of things to look into this PR:
The container image i am using is from docker, it requites curl and jq
related to #https://github.com/redhat-cop/pelorus/issues/36
related to #https://github.com/redhat-cop/pelorus/pull/227
> Adds Helm test for Grafana.

- .github/workflows/prometheus-rules.yml
Quick fix for prometheus rules testing in Github Actions
> use go modules for promtool

- exporters/requirements.txt
Due to a change in the kuernetes python package exporters deployed in pods were not able to access the Openshift API.  This fix ties our version of the Openshift/Kuberneets API to the last good working verison 0.11/11.0
resolves #257 
To test do a standard deployment of the exports to a cluster and verify all the exports are running and connecting to the Openshfit API.
> downgrade openshift due to kube client issue in v12

- exporters/committime/app.py
- exporters/committime/collector_azure_devops.py
- exporters/committime/collector_base.py
- exporters/committime/collector_gitea.py
- exporters/requirements.txt
Describe the behavior changes introduced in this PR
This PR add support for Gitea and Azure Devops as an source to get Lead time for change metric
Linked Issues?
resolves #260
resolver #189 
Testing Instructions
Please include any additional commands or pointers in addition to our standard PR testing process.
Gitea
1- Login into https://try.gitea.io/ using your github account
2- Execute the steps describe on this repo https://github.com/konveyor/pelorus/blob/master/labs/consultant/03-Exporters.md#configuring-exporters , but using your gitea account instead of github.
3- Configure GIT_PROVIDER env on the exporter as "gitea"
4- Create a commit and check Pelorus dashboard to see the metrics
Azure Devops
1. Create and account on azure devops
2- Execute the steps describe on this repo …
> Add committime exporter support fot Gitea and Azure DevOps

- docs/Development.md
- exporters/requirements-dev.txt
This change fixed the formatting issue we had in the release process section of the dev guide on readthedocs. See here:
https://pelorus.readthedocs.io/en/latest/Development/#release-management-process
It also adds some basic instructions for testing docs changes locally using mkdocs
Follow new the instructions at the bottom of the dev guide to view readthedocs locally.
> Fix release process formatting, add instructions for testing readthedocs

- .github/workflows/build-pelorus.yaml
Update the python base image on the GitHub action flow to ubi8/python-39 to be able to generate the Pelorus images
resolves #289 
The unit testing process remains the same
> Update python image to ubi8/python-39

- pyproject.toml
Addresses root cause of #305 
1. Install ansible roles in `samples` as per its README.
2. Run `pytest` in the root directory and see if it tries to run tests in `samples`.
> Only search for tests in exporters/tests

- docs/Configuration.md
- exporters/failure/app.py
- exporters/failure/collector_jira.py
This PR uses the `PROJECT` environment variable of the failure-exporter to set the list of project keys in JIRA to extract metrics.
This feature will be valuable when you have a large organization with hundreds of projects but you only want to extract metrics from a subset of them. Many projects in that large organization could be used for other kind of projects not related with IT or  software developed or deployed.
*NOTE*: I am not an python expert developer, so an enhancement of this could be define PROJECT, not only as a comma separated string, also as a regular expression. (Maybe a second iteration of this PR)
related to #304 
> Querying issues by a list of projects in JIRA

- .github/workflows/integration-tests.yml
- .github/workflows/unittests.yml
- exporters/committime/__init__.py
- exporters/committime/app.py
- exporters/committime/collector_base.py
- exporters/committime/collector_github.py
- exporters/tests/integration/test_committime.py
- exporters/tests/integration/test_committime_integration.py
- mocks/commitexporter_github.json
- pyproject.toml
Introduce a GitHub committime integration test and runs it during CI. This will run mockoon to mock the GitHub and OpenShift APIs.
There is currently a strange bug where running integration tests alongside unit tests will cause the integration tests to fail, but this doesn't happen when they're run separately. They're run separately in CI, so I'm not fully concerned, but I'm looking into it now.
Start mockoon's server, then run: `pytest -m integration`
To see the bug I mentioned, run: `pytest -m`
> Committime github provider integration test

- charts/operators/Chart.yaml
- charts/operators/templates/delete-csv-hook.yaml
- charts/operators/templates/installplan-approval-job.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/templates/dashboard-snapshot-cronjob.yaml
- charts/pelorus/templates/grafana-post-install-hook.yaml
- charts/pelorus/templates/grafana.yaml
- charts/pelorus/templates/prometheus-cr.yaml
- charts/pelorus/templates/tests/pelorus-grafana-test-job.yaml
Replace images that require entitlements with the upstream versions
registry.redhat.io/openshift4/ose-cli:v4.4 --> quay.io/openshift/origin-cli:4.8
registry.redhat.io/openshift4/ose-oauth-proxy:v4.5 --> quay.io/openshift/origin-oauth-proxy:4.8
registry.redhat.io/web-terminal-tech-preview/web-terminal-tooling-rhel8:1.0.1 --> quay.io/wto/web-terminal-tooling:1.2
resolves #311 
No extra instructions need it besides the regular testing process
> Replace images that require entitlements with the upstream versions

- _test/pre-commit
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- charts/pelorus/charts/exporters/values.yaml
- charts/pelorus/values.yaml
This will address the core issue we saw in  #303, where pinning your repo to a specific tag still has the exporters pointed at `master`-- causing things like python code versions and container versions to get out of
sync.
Making `stable` the default will make for a better user experience, especially for updates.
I've created the [stable branch](https://github.com/konveyor/pelorus/tree/stable) which right now points to the same commit as the [v1.3.0](https://github.com/konveyor/pelorus/tree/v1.3.0) tag.
This also removes the appVersion from the chart. I don't think it makes sense to keep track of it exporter-wise, since users specify their own version with `source_ref`.
It might make sense to keep track of it for the grafana configuration? I can leave this change out if we want. …
> Set default exporter source_ref to "stable", remove appVersion from chart

- docs/Configuration.md
- docs/Demo.md
- docs/Development.md
- docs/Install.md
This PR:
- Documents changes to the release process, reflecting the work in #316 .
- Removes `source_ref` from examples, but adds a new example explaining how source_ref could be used.
- Fixes various formatting issues with the docs.
> Update docs for stable release, fix docs formatting

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- docs/Development.md
- docs/Install.md
The v.1.4.0 release didn't have an updated default tag.
I've fixed that, and another step in the release process that was missing.
> Fix default exporter ref pointing to old release

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
Fixed the error to find the remote ref, there is a tag with the name v1.4.1 and not 1.4.1
resolves #349 <-- Use this if merging should auto-close an issue
related to #349 <-- Use this if it shouldn't
> Invalid tag 1.4.1

- docs/Development.md
On some systems e.g. RHEL8.3 the pip version is not allowing to
install cryptography that is required as one of the sub-deps
for jira from requirements.txt. Upgrading pip in the venv
fixes the issue and it's not breaking system installed pip.
> Use newest version of pip CLI

- .github/workflows/python-formatting.yml
- .github/workflows/python-linting.yml
- Makefile
Fixes #363
Matrix of currently used in development python versions 3.9 and 3.10.
Makefile adjustments necessary to be compatible with github actions shell, that is missing 'command' and 'source'.
> Use of Makefile from github actions

- Makefile
- demo/demo-tekton
- scripts/pre-commit
- scripts/setup-pre-commit-hook
I made a typo in #353, making a bad shebang in ./scripts/setup-pre-commit-hook.
Shellcheck would have caught this.
While trying to figure out how to make shellcheck optionally run, I realized the pattern would work for chart-lint as well, so I added that.
> Optional shellcheck and chart lint

- exporters/committime/app.py
- exporters/committime/collector_github.py
Public repos do not need authentication.
This makes local testing and demoing the committime exporter much easier.
> Make no-auth github exporter okay

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
Describe the behavior changes introduced in this PR
We will release Pelorus 1.4.6, so two files requires version bump.
charts/pelorus/charts/exporters/templates/_buildconfig.yaml:
The default version will match TAG that will be created once this PR is merged.
charts/pelorus/Chart.yaml:
This requires incremental change as we did change the _buildconfig.yaml which belongs to the pelorus chart.
Next steps are to crate TAG and release that are described in the:
https://pelorus.readthedocs.io/en/latest/Development/#release-management-process
This is desired as we are going to merge PR #372, which will cause incompatibility with OCP <= 4.6, however that OCP version is no longer supported: OpenShift Life Cycle Dates
> New release 1.4.6

- Makefile
- docs/Development.md
- scripts/README.md
- scripts/install_dev_tools
New script which helps to setup dev-env and include required
non python CLI tools in the virtual environment.
Simply make dev-env && source .venv/bin/activate
Script can be also invoked outside of Makefile pointing to
different VENV.
Currently Linux and Mac OS X are working.
> Enhance dev-env to include needed tools such as oc or tkn #375

- .github/workflows/integration-tests.yml
Newest mockoon version is breaking CI, this work-around
pins the mockoon version to the 1.5.1 which we know worked fine.
It also introduces 120 retries of starting Mockoon as the issue
caused infinite loop.
related to #384 <-- Use this if it shouldn't
> Pin mockoon version to 1.5.1 to workaround #384

- exporters/committime/app.py
- exporters/committime/collector_base.py
- exporters/tests/integration/test_committime.py
- exporters/tests/test_deploytime.py
- exporters/tests/test_exporters.py
- pyproject.toml
Lack of .isort.cfg and explicit information about local packages
causes isort to fail. This addresses the issue, so now both
CI runs and local runs should be consistent.
> Ensure make format-check works on a local development env.

- .github/release-drafter.yml
Release drafter action configuration file
Adds release-drafter configuration file to create automatically drafts from the releases which can be approved or modified.
This configuration file must be merged before real drafter action is proposed, otherwise github workflow will fail.
> Release drafter configuration file

- .github/release-drafter.yml
- .github/workflows/release-drafter.yaml
Release drafter action to create releases in automated manner
Adds release-drafter action to create automatically drafts
for the releases which can be approved or modified.
Later another action could create releases from those drafts.
To bump major or minor version simply create PR with the
subject that contains "major release" or "minor release".
This action also auto-labels PRs based on some simple regex
which can be extended in the future.
> Release drafter action

- Makefile
BSD `find` requires the path to be first.
The order of actions and filters also matters, so -delete must be last.
`make clean-dev-env` now works on macOS.
Run `make clean-dev-env` on macOS.
Run `make clean-dev-env` on Linux to verify it still works the same there.
> Fix find in clean-dev-env for macOS

- .github/workflows/chart-lint.yml
- Makefile
- scripts/install_dev_tools
Partial fix for #374
Couple of changes required to make it happen:
- ensure install_dev_tools can selectively install CLIs as we don't want to install everything when running just chart-lint
- Change Makefile to use ct lint rather then charts.py
- Change github workflow file to use make chart-lint
- Introduce SKIP_PYTHON_CHECK in the Makefile. github actions python version with latest Ubuntu runner is at lower then required version.
> Use Makefile for chart-lint github action

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- docs/Install.md
New release of Pelorus, that makes it compatible with OpenShift 4.9
This release works only on the currently supported OpenShift versions
that is >=4.7.
> New minor release of Pelorus - requires OpenShift >= 4.7

- docs/MinIO.md
The MinIO docs had:
- two broken links
- a link to outdated OpenShift documentation
- a link to a missing page (which appears to just be the same page but renamed)
- in either case, the information is stale.
`mkdocs serve` or check the results of the ReadTheDocs github action.
> Fix and update links in MinIO

- Makefile
- docs/Development.md
- scripts/create_release_pr
Using script to calculate release versions and wrapping it around Makefile.
Developer has option to create major/minor/patch releases by simply
invoking make major-release / make minor-release / make release
commands and creating PR from changed by this process files.
> Easy release process

- Makefile
- scripts/README.md
- scripts/python-version-check.py
Also move version checking to separate script for cleanliness.
Python patch versions (3.10.PATCH) will no longer be checked.
This also moves the version checking into a separate script for cleanliness-- we no longer need to print and re-parse versions, and can do the simplest approach for major and minor version checking.
resolves #403
> Remove python patch version check

- .github/workflows/integration-tests.yml
- .github/workflows/python-formatting.yml
- .github/workflows/python-linting.yml
- .github/workflows/unittests.yml
Also add a version matrix to unit tests and integration tests.
This means that actions for certain python versions will not be cancelled if there's a failure with another version.
This makes it easier to diagnose python-version-specific issues.
This is a draft until the python version restriction issue is resolved.
> Disable fail-fast on all python github actions

- .github/workflows/build-pelorus.yaml
Related #63 and #358
Cleans up and improves workflow for building Pelorus images using GitHub actions. Main difference is to set correctly tags during build process rather then re-tagging them after they are built and moving number of common values to variables.
On top of that the image namespace is not included in the action itself, which easy testing of build actions in the forked repositories.
> Improves workflow for building Pelorus images

- exporters/requirements-dev.txt
- exporters/requirements.txt
Fixes #359
Scanned the code to check every usage of the particular
import, then used mixture of pipreqs and pipdeptree to find
appropriate packages.
Note that pipreqs can not be used for this project as some
dependencies found by this tool are obsolete, examples are
azure_storage, gitlab.
> Cleanup and documentation of the python requirements

- exporters/deploytime/app.py
- exporters/tests/openshift_mocks.py
- exporters/tests/test_deploytime.py
The deploytime exporter will now check a pod's `status.containerStatuses` for image IDs as well.
resolves #330
I'm planning on adding a simple mock for our deploytime exporter as well, which will have some images that don't have the ID in their spec.
- ~~[ ] I need to add the mock as mentioned above.~~
> Extract image SHAs from status.containerStatuses as well as spec.containers

- .github/workflows/chart-lint.yml
PR #406 showed that this dependency is important.
The chart-lint github action will now run when requirements-dev.txt is changed,
because that could affect the yamllint and yamale versions.
> Make chart-lint github action trigger on changes to requirements-dev.txt

- exporters/committime/__init__.py
- exporters/committime/collector_base.py
- exporters/pelorus/utils.py
- exporters/tests/test_utils.py
This adds `get_nested` and uses it to give us better error messages for the committime collector.
We often have to deal with heavily nested data, that may or may not be present or properly formed.  When something goes wrong, we often deal with unhelpful error messages like `AttributeError: None does not contain attribute foo`. This issue even motivated the python folks to give [better error messages for similar errors in 3.11](https://peps.python.org/pep-0657/).
Another problem is with how most validation / conversion processes work: if it fails at the first issue, then you fix that... and it just fails at the next issue... it'll take forever to get through. That's not necessary if later steps are independent of the earlier ones! The python folks also recognize this issue and are …
> Better missing attribute errors

- exporters/committime/__init__.py
- exporters/committime/collector_base.py
- exporters/pelorus/__init__.py
- exporters/pelorus/utils.py
Adds more committime debug logs and adds some verbosity to debug logging in general.
Also skips Builds that aren't ready yet, without further inspection. This avoids cluttering logs for builds that have failed or haven't completed yet.
Closes #419.
> More commit debug logs, exit Build inspection early if not yet ready

- docs/Configuration.md
- exporters/failure/app.py
- exporters/failure/collector_jira.py
- exporters/failure/collector_servicenow.py
- exporters/tests/test_failure_exporter.py
- pyproject.toml
Added test which checks for the deprecated password authentication.
JIRA uses same method to authenticate in the cloud jira instance for both deprecated password authentication and token based auth.
This may lead to the situation where wrong API key is actually considered password and then failure exporter is presenting deprecation error.
This change also moves connection func to separate private one for easy testing and readibility + may in the future include more sophisticated auth methods.
Added proper headers to the files which were modified.
resolves #423
> Test to cover JIRA token and password authentication.

- .github/workflows/mockoon-tests.yml
- Makefile
- exporters/tests/integration/test_committime.py
- scripts/README.md
- scripts/install_dev_tools
- scripts/run-mockoon-tests
Split of mockoon tests from integration tests, which allows to run e.g. failure integration tests easilly from makefile.
This requires creation of new GitHub workflow to run the Mockoon tests separatelly.
Updated README.md to reflect current set of scripts in the scripts/ directory.
Added missing shell scripts in the Makefile, that required small nit change in the install_dev_tools script.
resolves #428
> Fix for issue #428 and some minor Makefile nits

- exporters/failure/app.py
- exporters/failure/collector_jira.py
- exporters/tests/test_failure_exporter.py
- pyproject.toml
Fix issue #278 - failure pod crashing
We should log error rather then crash pod if JIRA is missing type required by failure exporter. JIRA type may be added after pelorus deployment.
Depends on #424 
> Fix issue #278 - failure pod crashing

- scripts/run-mockoon-tests
Fix issue #430 to allow running Mockoon container without SELinux
SELinux causes EACCES: permission denied error to access /data folder in a container when it's not disabled. For running tests it's ok to run it with selinux disabled.
resolves #430
> Fix issue #430 to allow running Mockoon container without SELinux

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/values.yaml
The default values.yaml was missing exporters:
on the top line, making a little harder to just add
new configured exporters for users.
https://github.com/konveyor/pelorus/blob/master/docs/Configuration.md
> Remove duplicate charts values.yaml file

- exporters/pelorus/__init__.py
- exporters/pelorus/utils.py
- exporters/tests/test_pelorus.py
- exporters/tests/test_utils.py
Fix issue #448 to make handling of shell env vars consistently
Proposed change makes handling of shell env variables in a consstent way and moves the logic to one function, which may be easily adopted in the future development.
> Fix issue #448 to make handling of shell env vars consistently

- exporters/committime/collector_base.py
- exporters/tests/integration/test_committime.py
The issue with commit time exporter is that new namespace could not be registered because object created at the very first step by GitFactory assigned watched namespaces and they were not updated during lifetime of the application. Similar problem occurred when there were no NAMESPACES passed to the application in which case object was assigned with all namespaces, but never freed. This change fixes the issue where we don't associate instance variable and gather this value every time collector is generating metrics.
resolves #446
> Fix Issue #446 where committime exporter had to be restarted

- exporters/failure/app.py
- exporters/failure/collector_jira.py
- exporters/tests/test_failure_exporter.py
JIRA projecect with reserved key "FIRST" must be surrounded by quotes in order to work. This behaviour is also accepted for other project keys/names.
Fixes issue #450
Fixes issue #454 
This is also preparation for getting jql query from configmap or env variable after PR #445 is merged, but at the moment did not want to have many dependent PRs open.
> Fix JIRA query string to accept project FIRST and allow more then one project

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/configmaps/committime.yaml
- charts/pelorus/configmaps/deploytime.yaml
- charts/pelorus/configmaps/failuretime.yaml
- charts/pelorus/configmaps/pelorus.yaml
- charts/pelorus/values.yaml
- docs/Configuration.md
- docs/Install.md
- exporters/committime/app.py
- exporters/deploytime/app.py
- exporters/failure/app.py
- exporters/failure/collector_servicenow.py
- exporters/pelorus/__init__.py
Use ConfigMap as means for configuration
Exporters are configured in a similar way to secrets and are using OpenShift ConfigMap objects for their values.
Change backwards compatible to accept older values.yaml.
Depends on: https://github.com/konveyor/pelorus/pull/449
> Use ConfigMap as means for configuration

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
This will allow to check exporter pod statuses in easy way.
> Add readiness and liveness probes, associate exporter type label

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
In case both values are present in ConfigMap and Secret, one from Secret is being used. This is already documented in the ConfigMap example files, however logic in the deploymentconfig was vice-versa.
> Ensure values from secrets has higher precedence than from configmap

- docs/Configuration.md
- exporters/failure/app.py
- exporters/failure/collector_jira.py
- exporters/tests/test_failure_exporter.py
Fixes #440 and #439 to allow specify custom JQL issues search query via environment variable or Custom Resource and also allow to define custom resolution state to calculate JIRA failure metric.
resolves #440 #439
Unit tests and you can run the failure exporter with additional env. (example oun our pelorustest account):
```
export SERVER=https://pelorustest.atlassian.net/
export TOKEN=YOUR_TOKEN_TO_ACCESS_PELORUSTEST
export USER=your@username.com
export LOG_LEVEL=debug
export JIRA_JQL_SEARCH_QUERY='type in ("Bug") AND priority in ("highest","medium")'
export JIRA_RESOLVED_STATUS="done,to do"
python exporters/failure/app.py
```
> Allow JIRA to define custom resolution field and search query

- .github/workflows/build-pelorus.yaml
- .github/workflows/pre-release.yaml
Re-tag latest released version with the 'stable' tag.
It also fixes failure exporter image.
resolves: #480
Testing was performed on a forked pelorus repository in the separate quay.io namespace, where all the images were correctly tagged during pre-release and release actions. Mixture of pre-release and release combinations on separate PRs and the same PR were performed to check possible use-cases. In all situations expected images were correctly tagged.
> Tag latest released version with 'stable' tag.

- scripts/run-pelorus-e2e-tests
curl prior to v7.76.0 had no --fail-with-body option, this change uses curl without such option. On top of that uses wget in situations where curl is not found.
> Ensure curl backwards compatibility in e2e tests

- scripts/run-pelorus-e2e-tests
CI has one shell env variable PULL_NUMBER which should be used while running e2e tests.
This change adds such check and ensures the PULL_NUMBER Is actual number before modyfing values.yaml file.
> Use PULL_NUMBER in e2e tests scripts

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- docs/Install.md
This release is required to have "stable" tag in our images.
> Minor release of Pelorus 1.6.0

- Makefile
- scripts/run-pelorus-e2e-tests
Adds two scenario tests to the Makefile
- e2e-tests-scenario-1: run e2e-tests with latest quay images
- e2e-tests-scenario-2: run e2e-tests for deploytime exporter using different exporter install methods
Related #473 
> New scenario tests make targets

- scripts/run-pelorus-e2e-tests
Fixes #508, where script was failing silently with exit code 0, causing CI jobs to report success, where it should fail.
> Proper exit code from timeout function

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- exporters/pelorus/__init__.py
When the exporter is ran from the pre-built image, no OPENSHIFT_BUILT_* env variables are available.
There is also no information accessible from the image itself about the source code from which the image was built.
This change allows to include image name and tag, so we can print this information within exporter.
We also have knowledge about the image sha that we can easily identify the source code for it using standard oc describe commands:
To obtain information about the image, simple use:
```
oc describe pod -n pelorus <exporter_name>
oc describe pod -n pelorus deploytime-exporter
[...]
>     Image:          image-registry.openshift-image-registry.svc:5000/pelorus/deploytime-exporter@sha256:2574fb8ea74e7ceca6033a0bac75b3ca1581c34fc06c6b79bc755cbd9a6e6d15
```
> Nit change to inform that exporter is ran from image.

- scripts/run-pelorus-e2e-tests
* remove oc apply configmaps from ci because the
documented install does not apply configmaps in a seperate step yet.
> remove oc apply configmaps from ci

- scripts/install_dev_tools
Makes the install_dev_tools script handle arm64 macs.
resolves #519
Remove your `.venv` and re-run `make dev-env`. Make sure all the necessary dev tools are present.
> Add install_dev_tools support for arm macs

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/thanos-rbac.yaml
- charts/pelorus/values.yaml
Change that moves the default labels that are being used in the thanos-rbac.yaml inside that Thanos ClusterRoleBinding yaml file.
This is nothing more then a bit of cleanup for the values.yaml.
> Move default labels from helm pelorus example values.yaml

- scripts/run-pelorus-e2e-tests
This is useful when e2e are failing, so we know why the pods are in crash state.
Deploy e2e tests with wrong secret...
> Show logs from crashing pods for e2e tests

- charts/pelorus/Chart.yaml
- charts/pelorus/configmaps/committime.yaml
- charts/pelorus/secrets/github_example.yaml
- docs/Configuration.md
- docs/Development.md
- exporters/committime/app.py
- exporters/pelorus/__init__.py
- exporters/tests/test_pelorus.py
- labs/consultant/03-Exporters.md
- mocks/README.md
- samples/todolist_commit_deploy.md
- scripts/run-pelorus-e2e-tests
Change which renames GIT_USER to USER and GIT_TOKEN to TOKEN, however ensures backwards compatibility with the old value names.
This makes all the exporters use same USER and TOKEN value names rather than failure using USER and commit time using GIT_USER.
> Rename GIT_USER and GIT_TOKEN to be consistent across exporters

- scripts/run-pelorus-e2e-tests
Allow to use all deployed exporters as a base to run validation curl against them. This allows to have generic script that works with multiple deployment types.
> Use generic method to validate exporters in e2e tests

- charts/operators/Chart.yaml
- charts/operators/templates/grafana-subscription.yaml
Grafana operator is installed from the community-operators that is available at:
https://operatorhub.io/operator/grafana-operator
Change to bump the version to the newest available version from the v4 channel which we are using.
> Update grafana to the newest available version from v4 channel

- scripts/run-pelorus-e2e-tests
when testing w/ openshift/release things were failing because the
change ref was from release and not pelorus.  Causing:
Cloning "https://github.com/konveyor/pelorus.git" ...
error: fatal: couldn't find remote ref refs/pull/29693/head
> only change values.yml ref: master to PR if repo is pelorus

- docs/dashboards/SoftwareDeliveryPerformance.md
Change to reflect current implementation in docs.
Fixes #140
This is only doc review as implementation already uses "sdp:".
> [docs] Change the prefix for the failure metrics to sdp

- docs/Configuration.md
- docs/Install.md
* authentication to remote services is NOT required with the default
install, so why confuse users in their first steps.
* consolidate the authentication doc in configuration.md
resolves #537 
> consolidate authentication for exporters in the Configuration.md doc

- scripts/install_dev_tools
Disabling helm checksum checking may improve pass ratio in the CI.
> Disable helm checksum checking as it's flake in CI

- scripts/install_dev_tools
Allows to install "noobaa" CLI as part of the dev-env, which is needed for the S3 bucket testing and development.
> Install noobaa CLI as part of dev-env

- Makefile
Currently e2e tests are using dev-env, that contains all dependencies even those that are not required to run those tests. Adding separate makefile target allows to save time and space while creating env for running those tests.
This hopefully reduces flake issues in periodic CI jobs.
> Make e2e tests use simplified environment

- exporters/committime/collector_gitlab.py
This change improves gitlab performance by allowing to call direct project by it's name within namespace. Previous implementation was searching for the project name, which was not effective and prone to errors if the project name was matching regex from all other gitlab projects.
Fixes #244 
> Improve gitlab performance by calling direct project

- charts/pelorus/Chart.yaml
- charts/pelorus/configmaps/committime.yaml
- charts/pelorus/configmaps/failuretime.yaml
- charts/pelorus/secrets/github_example.yaml
- charts/pelorus/secrets/jira_example.yaml
- docs/Configuration.md
- docs/Development.md
- docs/Install.md
- exporters/committime/__init__.py
- exporters/committime/app.py
- exporters/committime/collector_base.py
- exporters/committime/collector_bitbucket.py
- exporters/failure/app.py
- exporters/failure/collector_jira.py
- exporters/failure/collector_servicenow.py
- exporters/pelorus/__init__.py
- exporters/tests/test_pelorus.py
- labs/consultant/03-Exporters.md
- mocks/README.md
- samples/todolist_commit_deploy.md
resolves #464
Positive test:
1. Make a pelorus repo on bitbucket
2. Make an app password in bitbucket
3. Deploy a bitbucket committime collector using that bitbucket repo and credentials
4. Confirm that the metrics are logged / collected correctly
SSL Error test:
1. Keep the existing repo and deployment
2. Set up mockoon, enable TLS
3. Locally change the code so `git_server` is always overwritten with the local mockoon url
4. Verify the TLS/SSL error in the logs
Now, the negative test:
0. Remove the hardcoded git_server from the above test
1. Delete that repo
2. Redeploy the pod (don't rebuild!)
3. Confirm that the logs report the error and are fully detailed.
> Refactor bitbucket collector to not swallow errors & have nicer logging

- exporters/committime/collector_base.py
- exporters/failure/collector_base.py
Wes fixed the deploytime issue with this in #497. This just does it for committime and failure.
~~Still need to double check what _type_ it is, as we can't guarantee that the prometheus library will handle non-floats correctly.~~ Wes tried it and said it was good. We can revisit this if there's some type weirdness somewhere.
resolves #532 
resolves #533 
Set up committime and/or failure time exporters, and ensure that the values seen in grafana / prometheus are what you expect.
> Report resource timestamp as metric timestamp

- exporters/pelorus/__init__.py
- exporters/pelorus/config/DEVELOPING.md
- exporters/pelorus/config/README.md
- exporters/pelorus/config/__init__.py
- exporters/pelorus/config/_attrs_compat.py
- exporters/pelorus/config/_attrs_compat.pyi
- exporters/pelorus/config/common.py
- exporters/pelorus/config/converters.py
- exporters/pelorus/config/loading.py
- exporters/pelorus/config/log.py
- exporters/tests/test_config.py
- exporters/tests/test_utils.py
Relates to #554.
This adds the module responsible for the approach, with docs and tests. Integrating it with each exporter will come in a separate PR if we think this is a good approach.
> Unified config management and parameter logging: implementation before integration

- scripts/install_dev_tools
HELM installation fails in CI as a flake, we do fallback to the pinned version if the latest version can not be found during API call or the helm is not found in the $PATH after first installation atempt.
> Add fallback when installing helm CLI

- Makefile
Currently installation of helm is failing, because .venv/bin is not found in the $PATH, this causes periodic job to fail.
Activating venv before running install script should fix the issue.
> Use venv in the e2e-tests-dev-env Makefile target

- exporters/requirements-dev.txt
pylava 0.3.0 is incompatible with new pyflakes (2.5.0). Pin pyflakes to the version which is working with pylava.
Resolves #584 
Upstream bug: https://github.com/pylava/pylava/issues/13
> Fix pylava traceback by pinning dependent pyflakes pip package

- exporters/committime/collector_azure_devops.py
- exporters/committime/collector_base.py
- exporters/committime/collector_bitbucket.py
- exporters/committime/collector_gitea.py
- exporters/committime/collector_github.py
- exporters/committime/collector_gitlab.py
Each committime exporter supports only one GIT provider.
Currently it's implemented in a way it tries to talk to all GIT URLs except well known other provires. This allows to collect data from self hosted GIT providers with custom fqdn.
Fix is to properly propagate error for unsupported by each individual class GIT providers.
resolves #577 
Setup exporter as in the bug and check the logs.
With the current implementation we get:
```
08-02-2022 12:46:12 WARNING  Missing data for CommitTime metric from Build pelorus/failure-exporter-1 in app failure-exporter: Skipping non GitLab server, found https://github.com
```
> Fix traceback for unsupported git providers

- exporters/committime/__init__.py
Fixes #590 which causes giturlparse to improperly parse git URI when ending with "/" e.g. https://github.com/konveyor/pelorus/ instead of https://github.com/konveyor/pelorus or https://github.com/konveyor/pelorus.git
> Ensure git URI does not end with "/"

- Makefile
- scripts/e2e-tests-templates/app.py
- scripts/e2e-tests-templates/build_binary_app
- scripts/run-pelorus-e2e-tests
Enabling the gitlab,gitea and bitbucket committime exporters.
The way it works it creates binary build and annotate it with the corresponding git URL and hash. Based on that specific commit time exporter back-end is collecting timestamp of the commit from the provider PI.
Fixes #582
> Allow to test gitlab,gitea and bitbucket committime exporters.

- Makefile
- demo/README.md
- demo/demo-tekton.sh
- demo/python-example/Dockerfile
- demo/python-example/response.txt
- demo/tekton-demo-setup/02-project.yaml
- demo/tekton-demo-setup/03-build-and-deploy.yaml
resolves #526 
resolves #478 
check out pull request
./demo-tekton <git_url>
> update Tekton demo with optional build types

- docs/Configuration.md
- exporters/committime/collector_gitea.py
Fixes issue #592, where gitea commit time default API URL contained wrong default API address resulting in double "api/v1".
Updated docs to match current implementation where GIT_API may be provided for Gitea, Azure DevOps and GitHub backends.
> Fix default FQDN for gitea committime collector.

- Makefile
Once PR #593 is merged we can enable gitea commit time exporter in the e2e tests.
> Enable gitea commit time exporter e2e test

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
minor release required by the #598. Enabling other exporters does need new quay images which are tagged as released ones.
> minor release - 1.7.0

- Makefile
Prow periodic CI job which runs out of quay images should include multiple git backends. This is done via annotation as github commit time exporter does build and deploy application, so we don't have to do it for every other supporter git APIs.
Depends On: https://github.com/konveyor/pelorus/pull/599
> Enable gitlab, gitea and bitbucket commit time exporter in periodic

- demo/README.md
- docs/Configuration.md
* seperate pelorus config into "overview" and "details"
* add more concrete examples for annotating a binary build
* point to the tekton demo as a doc resource for supporting
various build incantations.
resolves #510
> Add more doc for binary blds and annotations

- docs/Configuration.md
- docs/Install.md
- scripts/create_release_pr
Fixes #544
Users have options to define container images or GIT source as exporter installation methods. This documentation covers all possible cases.
This may be usefull when user will be asked to deploy or update exporter with custom image provided by developers or would want to use different releases for different exporter instances.
Small update to the release script to mention last released branch in the Install.md.
Testing: https://pelorus--608.org.readthedocs.build/en/608/Configuration/#exporter-installation-sources
> Documentation for different exporter installation methods

- exporters/deploytime/__init__.py
- exporters/deploytime/app.py
- exporters/extra/README.md
- exporters/extra/releasetime/app.py
- exporters/extra/releasetime/collector_github.py
- exporters/pelorus/__init__.py
- exporters/pelorus/config/README.md
- exporters/pelorus/config/converters.py
- exporters/pelorus/utils.py
- exporters/provider_common/github.py
- exporters/tests/test_deploytime.py
Creates a "deploytime" collector that treats github releases as releases for prod.
Open questions:
Do we allow a regex per-project to determine what's a "production" release? Do we need to handle draft releases?
related to #447
resolves #531
> GitHub deploy time (release) collector

- scripts/run-pelorus-e2e-tests
Sometimes e2e tests are leaving mongo-persistent-scc behind remove this SCC if exists before running e2e tests.
> Ensure mongo-persistent-scc is deleted in e2e tests

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/rbac.yaml
- charts/pelorus/configmaps/committime.yaml
- docs/Configuration.md
- exporters/committime/README.md
- exporters/committime/__init__.py
- exporters/committime/app.py
- exporters/committime/collector_base.py
- exporters/committime/collector_image.py
- exporters/tests/integration/test_committime.py
Resolves #371.
An Image from "image.openshift.io/v1" is a non namespaced object which can be used to gather commit time data where such is missing from the Build.
During build process Labels may be available that includes information about commit time which was used to builds such image:
https://docs.openshift.com/online/pro/dev_guide/builds/build_output.html#output-image-labels
If such information is missing we still allow to annotate Image to include required data for the Pelorus metrics.
1. Create Image in the OCP cluster (even demo or e2e tests may be used)
2. For the mongo-persistent image the Labels should be there and collection should happen, only label the image so pelorus knows it's within interest:
```
oc label image sha256:588fb67a63ccbadf245b6d30747c404d809a851551b67c615a18217 …
```
> Collect commit time based on the Image Label or annotation

- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- docs/Configuration.md
- exporters/committime/collector_gitlab.py
- exporters/extra/releasetime/collector_github.py
- exporters/pelorus/certificates.py
- exporters/tests/certs/conftest.py
- exporters/tests/certs/test_custom_certs.py
- exporters/tests/certs/utils/certs.py
- exporters/tests/certs/utils/https.py
Document how to use custom certificates, update charts with this functionality, and make the implementation simpler (dir based instead of env var based).
resolves #463
While the unit tests should be sufficient for request testing, you can verify that loading the certs in the cluster works as follows.
1. Create a certificate and put it in a configmap:
```shell
openssl genpkey -algorithm rsa -out privkey.pem
openssl req -new -key privkey.pem -x509 -days 1 -subj '/CN=the coolest project ever AKA pelorus' -out cert.pem
oc create configmap my-certs --from-file=cert.pem
```
2. Deploy a requests-based exporter (listed in the docs-- committime_github is an easy one). Make sure it has the certificate map referenced as in [the docs](https://pelorus--612.org.readthedocs.build/en/612/Configuration/ind …
> Requests custom certs docs and charts

- charts/pelorus/Chart.yaml
- charts/pelorus/configmaps/failuretime.yaml
- exporters/failure/app.py
- exporters/failure/collector_github.py
- exporters/pelorus/__init__.py
Issues in github for personal repos by default have the label "bug".
It is possible for an org or user to use any label to indicate a bug.
For example OpenShift changed the label "bug" to "kind/bug"
This change is meant to make the label used for issues only in Github.
Allow the user to override the label.
* log the bug label
* also added, log the app_label
A customer can set two labels on the github issue, the bug label and the app_label
resolves #547
Example of how I tested:
```
(.venv) [whayutin@thinkdoe pelorus]$ export PROVIDER=github
(.venv) [whayutin@thinkdoe pelorus]$ export TOKEN=ghp_<snip>
(.venv) [whayutin@thinkdoe pelorus]$  hstr -- 
export PROJECTS=weshayutin/mig-demo-apps,konveyor/pelorus
(.venv) [whayutin@thinkdoe pelorus]$ export …
```
> Allow user to override github bug label

- demo/tekton-demo-setup/03-build-and-deploy.yaml
- exporters/committime/collector_image.py
tekton s2i task provides no builds, buildConfig etc. The
only artifact is an image.  Enhance the labels2i tekton task
to also annotate w/ the commit time.
When creating a result in tekton for the commit time the result
has a new line.  Use strip() on the annotation label.
Use the image provider for the committime exporter, and execute 
```
./demo-tekton.sh -g https://github.com/konveyor/pelorus -b s2i -r master
```
results:
```
warnings.warn(
08-31-2022 11:54:05 INFO     Loading ImageCommittimeConfig, inputs below:
08-31-2022 11:54:05 INFO     date_format='%a %b %d %H:%M:%S %Y %z', default value; COMMIT_DATE_FORMAT was not set
08-31-2022 11:54:05 INFO     =====Using Image Collector=====
08-31-2022 11:54:05 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/co …
```
> Update tekton to label committime on image for s2itekton

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/prometheus-cr.yaml
- charts/pelorus/templates/thanos-query.yml
- charts/pelorus/templates/thanos-store.yml
- charts/pelorus/values.yaml
- docs/Install.md
- docs/Noobaa.md
This fixes issues with stanos-store side container not writing data to the s3 buckets.
Related issue #139 
1. Create pelorus namespace
2. Ensure noobaa is configured/deployed and bucket thanos is created
3. Deploy Pelorus with Thanos pointing to the noobaa s3 storage created
4. Ensure s3 bucket is not empty - typically takes 2h from the time of deployment (s3cmd command can be used: s3cmd ls s3://thanos). 
Example s3cfg file vars from < > can be gathered from the noobaa status --namespace pelorus:
```
$ cat ~/.s3cfg
[default]
host_base = <ExternalDNS> # e.g. s3-pelorus.apps.cluster-mpryc1502ocp49n.mpryc1502ocp49n.mg.dog8code.com:443
host_bucket = <Backing Stores/TARGET-BUCKET> #e.g. nb.1661336201734.mpryc1502ocp49n.mg.dog8code.com
access_key = <AWS_ACCESS_KEY_ID>
secret_key = …
```
> Ensure thanos uses same version across all required containers

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/prometheus-cr.yaml
- charts/pelorus/values.yaml
- docs/Install.md
Thanos does persist Prometheus data, however the data is stored in buckets every 2h. Prometheus PVC allows to continuously store data and be resiliant to prometheus operator restarts and upgrades allowing to keep the data safe.
Deploy pelorus with the following config options:
```
prometheus_storage: true # mandatory
prometheus_storage_pvc_capacity: 2Gi #optional
prometheus_storage_pvc_storageclass: "gp2" #optional
```
Check that the PVC were created:
```
oc get pvc -n pelorus
```
Fixes #622
> Add option to configure prometheus with PVC

- demo/tekton-demo-setup/03-build-and-deploy.yaml
Previously the git url was hardcoded for the demo to be konveyor/pelorus, update to take the specified
url from the script.
Testing:
1. fork konveyor/pelorus
2. git clone the fork in a new directory
3. execute `./demo-tekton.sh -g https://github.com/<fork>/pelorus -b buildconfig -r master`
> ensure buildConfig in tekton uses specified git url

- Makefile
- scripts/run-pelorus-e2e-tests
Adds two new exporters in the e2e tests:
- jira_committime, to cover standard JIRA query
- jira_custom_committime, to cover non-standard JIRA query and resolution status
Depends on: https://github.com/konveyor/mig-demo-apps/pull/92
> JIRA exporter coverage in e2e runs

- .github/workflows/build-pelorus.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- charts/pelorus/values.yaml
- docs/Configuration.md
Moves building, tagging and using images from new migtools namespace.
Adds experimental releasetime GitHub exporter images and example use in values.yaml.
Please review. Once everyone is happy we will need to update in this repository the following secrets and create release so images are built:
* QUAY_USERNAME
* QUAY_PASSWORD
* QUAY_IMAGE_NAMESPACE
> Use quay.io images from migtools namespace

- .github/workflows/build-pelorus.yaml
Small nit which fixes build of the pelorus-releasetime-exporter.
> Fix id of the action used to build pelorus-releasetime-exporter

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/templates/_buildconfig.yaml
- docs/Install.md
minor release (1.8.0) with modified location of the Pelorus Quay images.
Current location for the four exporters:
https://quay.io/repository/migtools/pelorus-committime-exporter
https://quay.io/repository/migtools/pelorus-deploytime-exporter
https://quay.io/repository/migtools/pelorus-failure-exporter
Experimental exporter:
https://quay.io/repository/migtools/pelorus-releasetime-exporter
> minor release for new quay.io migtool image location.

- Makefile
- scripts/run-pelorus-e2e-tests
New flags and env variables to control enablment of the Thanos in the e2e tests.
Script expects either the env values:
export s3_access_key=<api_key>
export s3_secret_key=<s3_secret_key>
export s3_host=<s3_host>
export s3_bucket=<s3_bucket>
Or the folder_path specified by -c flag with the files containing the values: /folder_path/s3_access_key
/folder_path/s3_secret_key
/folder_path/s3_host
/folder_path/s3_bucket
Example runs:
./scripts/run-pelorus-e2e-tests -t -o konveyor
./scripts/run-pelorus-e2e-tests -t -c /var/run/pelorus/s3amazon/
./scripts/run-pelorus-e2e-tests	-t -o konveyor -e failure,gitlab_committime,gitea_committime
> Add option to enable Thanos in the e2e script

- exporters/committime/app.py
- exporters/deploytime/app.py
- exporters/extra/releasetime/app.py
- exporters/failure/app.py
- exporters/pelorus/__init__.py
- exporters/tests/test_config.py
Addressing feedback from https://github.com/konveyor/pelorus/pull/615#pullrequestreview-1107138110 (and solving personal annoyances)
The logging system is now configured as part of exporter startup. Previously it was a side-effect of importing pelorus (bad!)
> Make logging set up part of exporter startup, not import side effect

- Makefile
Small nit which caused scenario-2 jobs running PR type of tests instead of real different deployment methods.
$ make e2e-tests-scenario-2
```
$ oc get pods -n pelorus
NAME                                                   READY   STATUS      RESTARTS      AGE
committime-exporter-1-deploy                           0/1     Completed   0             27m
committime-exporter-1-j2mvb                            1/1     Running     0             27m
deploytime-exporter-2-956x6                            1/1     Running     0             27m
deploytime-exporter-2-deploy                           0/1     Completed   0             27m
git-custom-source-ref-committime-exporter-1-build      0/1     Completed   0             27m
git-custom-source-ref-committime-exporter-1-deploy     0/1     Completed …
```
> Fix to ensure scenario-2 are running different deployments

- .github/pull_request_template.md
- .github/release-drafter.yml
- docs/UpstreamSupport.md
Updates the Upstream Support to include covered backends. Adds proper labeling to the release drafter
Removes wrong statements from the PR template.
> Update to the Upstream Support, PR template

- exporters/pelorus/utils.py
- pyproject.toml
- scripts/troubleshooting/missing_labels.py
Add a script to check for mislabeled resources.
Docs will be in a separate PR.
related to #549
1. deploy some builds, pods, and replicationcontrollers. I used the usual todolist-mongo-go.
2. Run the script against `mongo-persistent` with `--for-exporter committime deploytime` to verify that there are no issues.
3. Manually remove the `app.kubernetes.io/name` label from a pod in that namespace.
4. Run the script and verify it complains about the missing label.
5. Add the label back, and then remove that label from the pod's replicationcontroller.
6. Run the script and verify it complains about the missing label.
7. Add the label back, and remove the label from the build that created the image for that pod.
8. Run the script and verify it complains about the missing label.
> Troubleshooting script

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/prometheus-cr.yaml
- charts/pelorus/values.yaml
- docs/Install.md
Allow to set Prometheus retention to configurable value, which defaults to 1y.
> Add option to configure Prometheus retention

- demo/README.md
- demo/tekton-demo-setup/02-project.yaml
- demo/tekton-demo-setup/03-build-and-deploy.yaml
* verify the basic-python app is running
* verify the latest commit deployed is in the committime log
* update the pipeline permissions w/ route access
* s2i requires committime exporter w/ provider=image
* Update Readme
> verify both the app and pelorus w/ tekton

- demo/demo-tekton.sh
- demo/tekton-demo-setup/03-build-and-deploy.yaml
Allows to run Tekton demo in automated fashion by passing number of runs and time between them on the CLI as follows:
-n flag for no-human re-runs
-c flag for count of runs
-t time between subsequent runs
E.g.:
./demo-tekton.sh -g https://github.com/mpryc/pelorus -b buildconfig -c 5 -t 600 -n
Adds timeout for the git clone tekton Task in situation where PV is br8ken. 1minute is way over the usual clone time which finishes in 2-3seconds.
```
export PELORUS_FORK=https://github.com/mpryc/pelorus
export NEW_BRANCH=pelorus_test_1
git clone  "${PELORUS_FORK}" pelorus-test
pushd pelorus-test
git checkout -b "${NEW_BRANCH}"
pushd demo
export KUBECONFIG=.........
./demo-tekton.sh -g "${PELORUS_FORK}" -b buildconfig   -c 7 -t 600 -n
```
> Automate tekton subsequent runs, add timeout for git clone

- charts/pelorus/Chart.yaml
- charts/pelorus/templates/prometheus-cr.yaml
- charts/pelorus/values.yaml
- docs/Install.md
Option to configure maximum storage capacity for the Prometheus.
This is addition to already configurable time retention.
> Add option to configure Prometheus maximum storage capacity

- scripts/run-pelorus-e2e-tests
Adds simple Thanos s3 bucket validation to the e2e script.
run script with thanos enabled or allow e2e job to finish and check logs for deploy count that should be greater than 1, because 1 is data which is from the current run.
```
Thanos query host: thanos-pelorus-pelorus.apps.cluster-mpryc1502ocp49n.mpryc1502ocp49n.mg.dog8code.com
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   195  100   106  100    89    298    250 --:--:-- --:--:-- --:--:--   550
Deploy count: 3
Cleaning up temporary files
```
> Validation of Thanos data in e2e script

- charts/operators/Chart.yaml
- charts/operators/templates/grafana-subscription.yaml
- charts/operators/templates/installplan-approval-job.yaml
Before we release MVR, bumping to the latest operator version of the grafana service.
> Bump grafana version to the newest one.

- exporters/committime/__init__.py
- exporters/committime/collector_azure_devops.py
- exporters/committime/collector_bitbucket.py
- exporters/committime/collector_gitea.py
- exporters/committime/collector_github.py
- exporters/committime/collector_gitlab.py
- exporters/committime/collector_image.py
- exporters/deploytime/__init__.py
- exporters/deploytime/app.py
- exporters/failure/collector_base.py
- exporters/failure/collector_github.py
- exporters/failure/collector_jira.py
- exporters/failure/collector_servicenow.py
- exporters/pelorus/__init__.py
- exporters/pelorus/timeutil.py
- exporters/provider_common/github.py
- exporters/provider_common/openshift.py
- exporters/tests/test_datetime.py
- exporters/tests/test_exporters.py
- exporters/tests/test_failure_exporter.py
- exporters/tests/test_pelorus.py
Fix timestamp parsing.
Timestamp parsing previously suffered from two issues:
1. The timezone was _replaced_ with UTC. This meant that any datetimes from other time zones were converted to incorrect times.
2. If fixed with using `astimezone`, then any timezone-naive timestamps _assumed the local system timezone_. This meant they were not only wrong, but wrong in different ways depending upon the time zone!
This now differentiates between three use cases:
1. The timezone is in the parsed datetime, and we expect that.
2. The timezone is not in the parsed datetime, and we explicitly say that it is UTC.
3. The format is user-supplied, and we can't be sure if it's aware or not. We will have to assume any timezone-aware datetimes are correct, and if they're naive, they are meant to be UTC. …
> timestamp timezone fix

- docs/Configuration.md
- exporters/committime/collector_image.py
- exporters/pelorus/timeutil.py
- exporters/tests/test_datetime.py
For the images that were build without commit time or hash data we allow to annotate them for the Commit Time exporter to work properly. This change allows to annotate with EPOCH time format.
> Allow to use EPOCH timestamp in the image annotation

- demo/README.md
- demo/tekton-demo-setup/03-build-and-deploy.yaml
- demo/tekton-demo-setup/tekton_demo_values.yaml
Use epoch for commit timestamp
Updated README
Added an example values.yaml file
> update tekton to use epoch

- exporters/deploytime/app.py
Change that adds to the deploytime continous time series for the active deployments.
Deployment with a timestamp creates an event, which may be in the past. Having just an event we are unable to make calculations based on the currently active deployments, because one may be gone from the cluster.
Adding deployment_active metric to already existing deploy_timestamp will allow to better visualize Lead Time for Change, where the "dots" are connected to each other, plus in the future we may be able to answer additional questions such as how many deployed apps are still working.
On top of that this change ensures one metric is presented only one time in the series rather then multiple times. The metrics were gathered several times multiplied by the number of found unique deployments.
Fixes …
> Adds continous metric to the deploytime

- demo/demo-tekton.sh
- demo/tekton-demo-setup/05-build-and-deploy.yaml
Couple of changes:
1. Tekton demo can ran from local source tree (without -g flag).
2. Running with -g flag ensures modifications to the pelorus git project happens in the temporary directory and not local source tree
3. Better handling of branches:
- if remote branch exists, use it
- if remote branch does not exists, create one
4. Cleanup function added.
5. Ensure we don't pollute master branch.
Local directory run:
clone pelorus fork, run demo on existing branch or non-exising, e.g.
```
git clone git@github.com:mpryc/pelorus.git
cd pelorus
./demo-tekton.sh -r non_existing_remote_branch -c 3
./demo-tekton.sh -r existing_remote_branch -c 3
```
Temp directory
- This is better as it works without polluting any of current files/branches from …
> Tekton demo improvements

- demo/demo-tekton.sh
* not having the pv and pvc cleaned up will cause the demo to fail
* message user and delete both the pvc and pv
Note: this is getting cumbersome to clean $everything to keep the pipeline history but I suppose we're done now.  This is to be compared to just nuking the namespace.
> clean up pv && pvc prior to execution

- exporters/committime/__init__.py
- exporters/committime/collector_bitbucket.py
- exporters/tests/integration/conftest.py
- exporters/tests/integration/test_bitbucket.py
- mocks/bitbucket_cloud.json
Add back bitbucket API version 1.0 support. Adds it back in a refactored way to separate version-specific behavior
resolves #678 
~~/hold until tested by the reporter of #678~~
> Add back bitbucket API version 1.0 support.

- scripts/get_github_dl_url.py
- scripts/install_dev_tools
- Allows running `./scripts/install_dev_tools operator-sdk` to install the [operator sdk](https://sdk.operatorframework.io/)
- Moves github release url extraction to a separate python script
- this is done because adding yet another exception to the URL extraction code was going to get messy.
1. `./scripts/install_dev_tools operator-sdk`
2. `which operator-sdk`
> Add operator-sdk support to dev env, add release URL extraction python script

- Makefile
- scripts/install_dev_tools
With the fix for #676 we can now replace shell function with it's python equivalent.
```
make dev-env
```
> Replace shell get_download_url_from_github_api function

- Makefile
Makes social card generation from #695 work on macOS with a default dev-env.
Run `make dev-env && . .venv/bin/activate && mkdocs serve`
> Add system-level doc dependencies to dev-env setup

- README.md
- docs/index.md
Update the documentation index file (which is rendered in https://pelorus.readthedocs.io/en/latest/) to be up to date with the README file.
no.
Run `mkdocs serve` to see how it renders.
> fix: Update documentation index file

- .github/workflows/build-pelorus.yaml
- .github/workflows/chart-lint.yml
- .github/workflows/conftest.yaml
- .github/workflows/integration-tests.yml
- .github/workflows/mockoon-tests.yml
- .github/workflows/pre-release.yaml
- .github/workflows/prometheus-rules.yml
- .github/workflows/python-formatting.yml
- .github/workflows/python-linting.yml
- .github/workflows/release.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/unittests.yml
Updates the checkout and python github actions we use. This is to avoid bitrot, and get rid of deprecation warnings.
This also now lets us cache python dependencies-- now if you have actions run again for the same PR, it will reuse those dependencies unless any of the requirements files changed.
resolves #711
See GitHub actions and verify that they are working properly.
> Update GH actions, cache python deps

- scripts/get_tool_dl_url.py
- scripts/install_dev_tools
Pin `oc` on macs to 4.10 to work around a golang x509 bug.
Also install the arm version of `oc` on arm macs.
resolves #707
1. Delete `.venv/bin/oc`
2. Run `make .venv/bin/oc`
3. Verify it installs correctly.
If on a mac:
1. Follow the above
2. try connecting to an OpenShift cluster with untrusted certs
3. run `file .venv/bin/oc` and verify it is arm formatted.
> Pin macOS oc version to 4.10, download ARM on ARM macs

- .github/workflows/typecheck.yml
- Makefile
- exporters/requirements-dev.txt
- scripts/pre-commit
We're not running it as part of pre-commit yet so we don't get error fatigue. ~~Unfortunately, it doesn't seem like there's an easy way to mark a check as a "warning": https://github.com/actions/toolkit/issues/399~~. Never mind! We can just mark the check as not required for merging.
Adds a type check target and runs type checking in CI.
Type checking is not a hard requirement, and is just informational right now.
related to #708
See CI logs.
To run it yourself, update your venv, make sure you have node installed on your system, and run `pyright`.
If you use VS Code and the python extension, you're probably already using pyright!
> Introduce the start of automatic type checking

- scripts/README.md
- scripts/create_pelorus_operator
- scripts/pelorus-operator-patches/01_podman_makefile_tool.diff
- scripts/pelorus-operator-patches/02_makefile_image_url.diff
- scripts/pelorus-operator-patches/03_pelorus_operators_roles.diff
The intention of this script is to easy recreate operator files and ensure new version of operator-sdk can be used with our mods.
This script expects clean output directory where the operator will be generated.
Ensure you have correct helm charts (from the https://github.com/mpryc/pelorus-operator/tree/master/operator/helm-charts/pelorus-operators). Once they will be clean in the pelorus repo we will use them from default location.
$ source .venv/bin/activate
$ mkdir /tmp/operator
$ mkdir /tmp/generated-operator
$ pushd /tmp/operator
$ git clone git@github.com:mpryc/pelorus-operator.git
$ popd
$ ./scripts/create_pelorus_operator -h
$ ./scripts/create_pelorus_operator -s /tmp/operator/pelorus-operator/operator/helm-charts/pelorus-operators -d …
> Script to create new operator from already existing helm charts

- exporters/committime/collector_azure_devops.py
- exporters/tests/test_exporters.py
resolves #724 
w/ fix:
```
11-18-2022 17:07:17 INFO     Loading CommittimeTypeConfig, inputs below:
11-18-2022 17:07:17 INFO     provider='git', from env var PROVIDER
11-18-2022 17:07:17 INFO     Loading GitCommittimeConfig, inputs below:
11-18-2022 17:07:17 INFO     username='whayutin', from env var API_USER
11-18-2022 17:07:17 INFO     token=REDACTED, from env var TOKEN
11-18-2022 17:07:17 INFO     namespaces='mongo-persistent,basic-python-tekton', from env var NAMESPACES
11-18-2022 17:07:17 INFO     git_api='https://dev.azure.com/whayutin', from env var GIT_API
11-18-2022 17:07:17 INFO     git_provider='azure-devops', from env var GIT_PROVIDER
11-18-2022 17:07:17 INFO     tls_verify=True, default value; TLS_VERIFY was not set
11-18-2022 17:07:17 INFO     Watching namespaces: …
```
> azure-devops: fix url connection string

- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
A wrong bundle version was causing improper installation.
$ cd operator-sdk
$ operator-sdk run bundle quay.io/migtools/pelorus-operator-bundle:v0.0.1 --namespace pelorus
> Fix pelorus-operator versioning within bundle

- pelorus-operator/Dockerfile
- pelorus-operator/Makefile
- pelorus-operator/bundle.Dockerfile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/bundle/metadata/annotations.yaml
- pelorus-operator/bundle/tests/scorecard/config.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/rbac/pelorus_manager_role.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/config/scorecard/patches/basic.config.yaml
- pelorus-operator/config/scorecard/patches/olm.config.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- scripts/pelorus-operator-patches/03_pelorus_operators_roles.diff
This fixes 742 issue where rbac was not sufficient to deploy exporters using source instead of quay images.
```
$  operator-sdk run bundle quay.io/migtools/pelorus-operator-bundle:v0.0.5 --namespace pelorus
- app_name: committime-exporter
exporter_type: committime
env_from_secrets:
- github-secret
source_ref: master
source_url: https://github.com/konveyor/pelorus.git
```
> RBAC permissions for the deployment from source

- scripts/pelorus-operator-patches/06_ocp_manager_resources.diff
With this change we use kustomization on the manager rather than on the patched version of the manager.
The patched version was also OK, however this is cleaner as we don't patch another patch.
> Update resources for the manager

- scripts/pelorus-operator-patches/03_pelorus_operators_roles.diff
Adding rbac to cover installation methods that requires Thanos sidecar.
> Thanos rbac for the pelorus-operator

- pelorus-operator/Dockerfile
- pelorus-operator/Makefile
- pelorus-operator/bundle.Dockerfile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/bundle/metadata/annotations.yaml
- pelorus-operator/bundle/tests/scorecard/config.yaml
- pelorus-operator/config/default/manager_auth_proxy_patch.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manager/manager.yaml
- pelorus-operator/config/rbac/pelorus_manager_role.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/config/scorecard/patches/basic.config.yaml
- pelorus-operator/config/scorecard/patches/olm.config.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
Version 0.0.9 based on operator-sdk v1.26.0, that includes RBAC updates for the Thanos scenario.
```
1: Install operator
$ operator-sdk run bundle quay.io/migtools/pelorus-operator-bundle:v0.0.9 --namespace pelorus
2: Log in to the UI and create instance of the freshly installed Pelorus Operator
```
> New pelorus operator version 0.0.9

- scripts/create_pelorus_operator
As found by @mateusoliveira43 there was duplication of logic in our Pelorus operator script to echo versions.
Fixed as well instructions that includes new bundle method.
> Fix pelorus operator script to add proper instructions and remove dup

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/subcharts/exporters/Chart.yaml
- charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
- charts/pelorus/subcharts/exporters/templates/exporters.yaml
- charts/pelorus/values.yaml
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/charts.pelorus.konveyor.io_pelorus.yaml
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/crd/bases/charts.pelorus.konveyor.io_pelorus.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/exporters.yaml
- pelorus-operator/helm-charts/pelorus/values.yaml
- scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
- scripts/pelorus-operator-patches/07_spec_description.diff
A number of fixes in this revision:
- Changed logo
- Added descriptions and fields to the openAPIV3Schema
- Updated example to include all 3 exporters
- added "enabled:" field for the exporter to allow enabling or disabling exporter from the values.yaml or the openAPIV3Schema
- Added metadata and categories for the Marketplace
`operator-sdk run bundle quay.io/migtools/pelorus-operator-bundle:v0.0.38 --namespace pelorus`
> Pelorus community operator fixes

- exporters/pelorus/deserialization/__init__.py
- exporters/pelorus/deserialization/errors.py
- exporters/pelorus/utils/__init__.py
- exporters/pelorus/utils/nested.py
- exporters/requirements.txt
- exporters/tests/test_deserialization.py
- exporters/tests/test_utils.py
1. kubernetes dynamic `ResourceField`s support `__getitem__`. However, you can't do a `issubclass` check on a `Mapping`, unlike some other "magic" checks. This replaces the `issubclass` / `isinstance` work with a simple attribute lookup.
2. Sometimes, keeping the source of the deserialization is useful. A new metadata option has been added for that.
This helps support the work in #720 .
Run unit tests as usual.
> Deserialization: allow retaining source, fix getitem handling

- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- scripts/create_pelorus_operator
- scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
- scripts/pelorus-operator-patches/07_spec_description.diff
Pelorus Operator which is the candidate for the Community Operator
To install:
```operator-sdk run bundle quay.io/pelorus/pelorus-operator-bundle:v0.0.1 --namespace pelorus```
> Pelorus Operator v0.0.1 - Community Operator candidate

- .github/pull_request_template.md
- CONTRIBUTING.md
- docs/Architecture.md
- docs/Configuration.md
- docs/Development.md
- docs/Noobaa.md
- docs/index.md
- docs/philosophy/outcomes/SoftwareDeliveryPerformance.md
Fix some typos in documentation.
No.
Run the documentation locally, with
```
make dev-env
source .venv/bin/activate
mkdocs serve
```
> fix: Documentation typos

- .github/workflows/mockoon-tests.yml
- scripts/run-mockoon-tests
Remove the behavior of silently fail from the mockoon script.
No.
Check CI logs for the mockoon job and run `make mockoon-tests` locally.
> fix: mockoon script failing silently

- exporters/failure/collector_github.py
#775 
resolves #775
label a github issue w/o an "=" 
> Fix github label trace

- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/charts.pelorus.konveyor.io_pelorus.yaml
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/bundle/metadata/properties.yaml
- pelorus-operator/config/crd/bases/charts.pelorus.konveyor.io_pelorus.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/watches.yaml
- scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
- scripts/pelorus-operator-patches/07_spec_description.diff
- scripts/pelorus-operator-patches/08_watches_dependent_resources.diff
Pelorus Operator that addresses #777
To test:
`operator-sdk run bundle quay.io/pelorus/pelorus-operator-bundle:v0.0.2 --namespace pelorus`
> Pelorus Operator v0.0.2

- doc_update.exporters.diff
- docs/GettingStarted/configuration/ExporterDeploytime.md
Improved docs for the Deploy Time Exporter.
Testing: https://pelorus--789.org.readthedocs.build/en/789/GettingStarted/configuration/ExporterDeploytime/
> Changes to the Deploy Time Exporter doc

- scripts/run-pelorus-e2e-tests
We have multiple pods of the same type, so current logic was not perfect as we were waiting for the first pod of the type to continue our run.
We should wait for all pods to become ready.
> Add logic to the CI where the pod was not ready.

- docs/GettingStarted/configuration/PelorusCore.md
- docs/GettingStarted/configuration/ProductionBestPractice.md
Production Best Practices have too much duplicated information that can be only referenced to the proper doc sections.
https://pelorus--795.org.readthedocs.build/en/795/GettingStarted/configuration/ProductionBestPractice/
> Production Best Practices doc rework

- .readthedocs.yaml
- mkdocs.yml
Konveyor video available at:
https://youtu.be/VPCOIfDcgso?t=212
Points to the:
http://pelorus.readthedocs.io/en/latest/Demo/
This change allows the link to be redirected to our current Demo/Quickstart Tutorial.
> Fix Demo link to work with the Konveyor demo

- exporters/pelorus/deserialization/__init__.py
- exporters/pelorus/utils/nested.py
- exporters/tests/test_deserialization.py
- pyproject.toml
Add more tests to deserialization module and also running doctests when running the test suite.
Resolves https://github.com/konveyor/pelorus/issues/754
run test and coverage command 
```
coverage run -m pytest -rap -m "not integration and not mockoon" && coverage html
```
to check tests and coverage.
> fix: add more tests to deserialization

- .coveragerc
- Makefile
- docs/Development.md
- exporters/requirements-dev.txt
- pyproject.toml
Run doctests and coverage only Pelorus python source code (excluding its tests) when running pytest.
Example with `make unit-tests` on master branch
Tests are considered part of the coverage, not all folders of exporters are present (like extra) in the coverage and doctests are not run.
Example with `make unit-tests` on this PR
Tests are NOT considered part of the coverage, ALL folders of exporters are present in the coverage and doctest are run.
No.
Check CI logs and run `make unit-tests`, `make mockoon-tests` and `make integration-tests` to check coverage information. All of them should have the same number of TOTAL Stmts (2183).
> fix: Tests config to run doctests and coverage right folders

- docs/GettingStarted/Installation.md
- docs/GettingStarted/QuickstartTutorial.md
- docs/GettingStarted/configuration/ExporterCommittime.md
- docs/GettingStarted/configuration/PelorusCore.md
- docs/GettingStarted/configuration/PelorusExporters.md
- docs/GettingStarted/configuration/ProductionBestPractice.md
Use description list instead of tabs in our docs (and fix some typos).
resolves #803
Check readthedocs CI job.
> docs: Use description lists instead of tabs

- .github/dependabot.yml
Let dependabot update github actions for us.
resolves #827
After we close the PR, we need to enable it, and then it will start working.
> feat: Add dependabot to project

- .github/workflows/integration-tests.yml
- docs/GettingStarted/configuration/ExporterFailure.md
- exporters/README.md
- exporters/committime/app.py
- exporters/committime/collector_base.py
- exporters/committime/collector_gitea.py
- exporters/committime/collector_image.py
- exporters/deploytime/app.py
- exporters/failure/collector_jira.py
- exporters/pelorus/deserialization/errors.py
- exporters/pelorus/utils/__init__.py
- exporters/tests/integration/test_committime.py
- exporters/tests/test_failure_exporter.py
Ignores missing projects when exporting JIRA issues. 
resolves #455
Uncomment the test in `exporters/tests/test_failure_exporter.py` with your credentials and run integration tests.
> fix: Allow missing projects in JIRA exporter

- scripts/create_pelorus_operator
- scripts/specify_operator_update.py
Automatically add replaces/skips sections to Pelorus Operator ClusterServiceVersion file when updating/creating the  Operator.
resolves #788 
run `rm -rf test_folder && mkdir test_folder && scripts/create_pelorus_operator -d test_folder` and check if the `test_folder/bundle/manifests/pelorus-operator.clusterserviceversion.yaml` has the desired sections from pelorus operator tags.
> feat: Automatically add replaces/skips to operator csv file

- exporters/committime/collector_base.py
Currently the commit time metric is yielding every commit row in a loop which results in duplicated rows in the Prometheus GaugeMetricFamily. This should be changed so the metrics are yielded at once and appearing in the /metrics of the exporter in a single place.
The current way causes number of rows to grow rapidly, let's say we have only `100` commits which should result in `100` rows, but in the current situation we would have `5050` rows, for `300` commits which isn't unusual instead of `300` rows we will get `45150` rows, so shortly we would cause entire commit time exporter to fail.
```
Cn - number of commits
Nseries = Cn/2 * (1 +Cn)
```
Current format, for each additional metric the commit_timestamp is duplicated, for just 4 commits:
```plain/text
process_max_fds 1024.0 …
```
> Commit time exporter should produce unique metric rows

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/subcharts/exporters/Chart.yaml
- charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
- charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
- docs/Development.md
- pelorus-operator/Dockerfile
- pelorus-operator/Makefile
- pelorus-operator/bundle.Dockerfile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/bundle/metadata/annotations.yaml
- pelorus-operator/bundle/tests/scorecard/config.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
- pelorus-operator/config/scorecard/patches/basic.config.yaml
- pelorus-operator/config/scorecard/patches/olm.config.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/default_configmaps.yaml
- scripts/create_release_pr
This is a new release 2.0.6 of the Pelorus with it's corresponding pelorus-operator version 0.0.3.
This is just a source for the new release created using the following three calls:
```shell
$ ./scripts/create_release_pr -v 2.0.6
$ rm -rf pelorus-operator && mkdir pelorus-operator
$ ./scripts/create_pelorus_operator
```
This does not automatically create two container images required by the pelorus-operator:
```
quay.io/pelorus/pelorus-operator
quay.io/pelorus/pelorus-operator-bundle
```
To create those, log in to the quay.io account and then:
```shell
$ cd pelorus-operator/
$ make podman-build
$ make bundle-build
$ make podman-push
$ make bundle-push 
```
> Updated release of the Pelorus with it's pelorus-operator.

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/subcharts/exporters/Chart.yaml
- charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
- charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
- docs/Development.md
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
Current version of pelorus-operator 0.0.3 is broken, we need to create new release 0.0.4 to fix the issue as in the #849.
Needed by #849 
Fix for the #849 requires creating new release in the openshift marketplace.
> New release of Pelorus with new pelorus operator to fix #849

- charts/pelorus/subcharts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
This fixes RBAC issues with the pelorus-operator 0.0.3.
There was another issue with the image tags within the image stream created for each individual exporter, which should be fixed by this PR.
No need to create new Release as the pelorus-operator and pelrus-bundle may be created without new github release.
1. Create new pelorus namespace
2. make sure you activated venv of pelorus project (master should do)
3. Run `operator-sdk run bundle quay.io/pelorus/pelorus-operator-bundle:v0.0.4`
4. Create instance of the pelorus operator
> Fix for broken RBAC in the pelorus-operator 0.0.3

- docs/GettingStarted/Overview.md
- docs/GettingStarted/configuration/ExporterFailure.md
- docs/index.md
- exporters/failure/app.py
- exporters/failure/collector_github.py
- exporters/failure/collector_pagerduty.py
- exporters/pelorus/errors.py
- exporters/pelorus/utils/__init__.py
- exporters/tests/__init__.py
- exporters/tests/test_failure_exporter.py
- exporters/tests/test_failure_exporter_app.py
- exporters/tests/test_failure_exporter_pager_duty.py
Add PagerDuty Failure Exporter to Pelorus.
| Variable | Required | Default Value |
|----------|----------|---------------|
| PROVIDER | yes | `pagerduty` |
| LOG_LEVEL | no | `INFO` |
| SERVER (tracker_api) | NOT USED | - |
| API_USER | NOT USED | - |
| TOKEN | yes | get it at `https://your_subdomain.pagerduty.com/api_keys` (Integration -> API Access Keys) |
| APP_LABEL | NOT USED | `app.kubernetes.io/name` |
| PROJECTS | NOT USED | - |
| PELORUS_DEFAULT_KEYWORD | no | `default` |
| PAGERDUTY_URGENCY | no | - |
| PAGERDUTY_PRIORITY | no | - |
**TODO write tests and docs:**
Ensure the requirements items in here were fulfilled https://github.com/orgs/konveyor/projects/51/views/2?pane=issue&itemId=20613492
Resolves #848 
To test PagerDuty …
> feat: Add PagerDuty Failure Exporter

- exporters/requirements-dev.txt
- exporters/requirements.txt
- exporters/tests/data/webhook_pelorus_committime.json
- exporters/tests/data/webhook_pelorus_deploytime.json
- exporters/tests/data/webhook_pelorus_failure_created.json
- exporters/tests/data/webhook_pelorus_failure_resolved.json
- exporters/tests/test_in_memory_metric.py
- exporters/tests/test_pelorus_base_plugin.py
- exporters/tests/test_pelorus_webhook.py
- exporters/tests/test_pelorus_webhook_handler.py
- exporters/tests/test_webhook_models.py
- exporters/webhook/README.md
- exporters/webhook/__init__.py
- exporters/webhook/app.py
- exporters/webhook/models/__init__.py
- exporters/webhook/models/pelorus_webhook.py
- exporters/webhook/plugins/__init__.py
- exporters/webhook/plugins/pelorus_handler.py
- exporters/webhook/plugins/pelorus_handler_base.py
- exporters/webhook/store/__init__.py
- exporters/webhook/store/in_memory_metric.py
Check README.md in the webhook folder.
Some testing instructions:
On one terminal:
```shell
$ make dev-env
$ source .venv/bin/activate
$ cd exporters/webhook
$ uvicorn app:app
```
On another terminal
```shell
$ cd exporters/tests/data
$ curl -X POST http://localhost:8000/pelorus/webhook -d @./webhook_pelorus_committime.json -H "Content-Type: application/json" -H "User-Agent: Pelorus-Webhook/test" -H "X-Pelorus-Event: committime"
$ curl -X POST http://localhost:8000/pelorus/webhook -d @./webhook_pelorus_deploytime.json -H "Content-Type: application/json" -H "User-Agent: Pelorus-Webhook/test" -H "X-Pelorus-Event: deploytime"
$ curl -X POST http://localhost:8000/pelorus/webhook -d @./webhook_pelorus_failure_created.json -H "Content-Type: application/json" -H "User-Agent: …
```
> Webhook exporter allowing Pelorus to work with push data model

- .github/workflows/build-pelorus.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- docs/Development.md
Covers building webhook exporter and pushing it to the quay.io repository for the commit, pre-release and release events.
Documentation will be covered as part of the #857, however here one link was added as it's directly pointing to the quay image which will be built by those actions.
Depends on: #836
> Add GitHub Actions to build the webhook exporter

- exporters/webhook/app.py
We use one server to serve both /pelorus/webhook and the /metrics for prometheus. They should run on the same port as other exporters.
> Update webhook port to 8080 to match other exporters

- docs/Architecture.md
- docs/Development.md
- docs/GettingStarted/Examples.md
- docs/GettingStarted/configuration/ExporterWebhook.md
- exporters/webhook/README.md
- mkdocs.yml
Updated documentation to cover usage of the pelorus webhook exporter with the examples on how to use
curl in a sample application lifecycle.
Fixes: #857 
> Pelorus webhook exporter doc

- charts/pelorus/Chart.yaml
- charts/pelorus/subcharts/exporters/Chart.yaml
- charts/pelorus/templates/prometheus-cr.yaml
- charts/pelorus/templates/prometheus-scrape-config-secret.yaml
- charts/pelorus/values.yaml
- demo/tekton-demo-setup/operator_tekton_demo_values.yaml.sample
- docs/GettingStarted/Installation.md
- docs/GettingStarted/configuration/PelorusCore.md
- scripts/pelorus-operator-patches/07_spec_description.diff
Add possibility of use scrape hosts from external cluster, or outside a cluster, with Pelorus.
https://github.com/orgs/konveyor/projects/51/views/2?pane=issue&itemId=20613515
Create Pelorus operator from this branch, by changing line 19 of `scripts/create_pelorus_operator` to `YOUR_QUAY_USER` and running
```
podman login ...
oc login ...
rm -rf pelorus-operator && mkdir pelorus-operator && scripts/create_pelorus_operator
cd pelorus-operator
make podman-build
make bundle-build
make podman-push
make bundle-push
oc delete namespace pelorus
oc create namespace pelorus
operator-sdk run bundle quay.io/<YOUR_QUAY_USER>/pelorus-operator-bundle:v0.0.1 --namespace pelorus
```
Then, create an instance of Pelorus with `federated_prometheus_hosts` and/or  `external_prometheus_hosts` options, to test …
> feat: Add external Prometheus host config option

- exporters/tests/test_in_memory_metric.py
- exporters/tests/test_webhook_models.py
- exporters/webhook/models/pelorus_webhook.py
We simplify the timestamp of the webhook pelorus plugin to accept only EPOCH timestamp.
It's up to the service sending POST data to ensure timestamp is a valid format and we do not have troubles converting them from unknown data format.
Fixes: #867 
Added test to capture wrong data and modify other tests to cover positive test case.
$ make unit-tests
> Fix the webhook timestamp validator

- .adr-dir
- docs/Development.md
- docs/adr/0001-record-architecture-decisions.md
- exporters/requirements-dev.txt
As proposed by @KevinMGranger in the #834, the ADRs are important part of the development cycle. This change adds some tooling that allows to create and manage ADRs easily.
https://pelorus--876.org.readthedocs.build/en/876/Development/#architectural-decision-records
> Template and the tooling for the ADRs

- charts/operators/Chart.yaml
- charts/pelorus/Chart.yaml
- charts/pelorus/subcharts/exporters/Chart.yaml
- charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
- charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
- charts/pelorus/values.yaml
- docs/Development.md
- pelorus-operator/Dockerfile
- pelorus-operator/Makefile
- pelorus-operator/bundle.Dockerfile
- pelorus-operator/bundle/manifests/charts.pelorus.konveyor.io_pelorus.yaml
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/bundle/metadata/annotations.yaml
- pelorus-operator/bundle/tests/scorecard/config.yaml
- pelorus-operator/config/crd/bases/charts.pelorus.konveyor.io_pelorus.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
- pelorus-operator/config/scorecard/patches/basic.config.yaml
- pelorus-operator/config/scorecard/patches/olm.config.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
- pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/helm-charts/pelorus/templates/prometheus-cr.yaml
- pelorus-operator/helm-charts/pelorus/templates/prometheus-scrape-config-secret.yaml
- pelorus-operator/helm-charts/pelorus/values.yaml
- scripts/create_pelorus_operator
Release for version `0.0.5` of Pelorus Operator.
related to #864 (It will be resolved once it is merged in community operator repository)
For changing helm verion (removing `v` from it), we ran
```
helm install operators charts/operators --namespace pelorus
helm install pelorus charts/pelorus --namespace pelorus --values charts/pelorus/values.yaml
```
Manually changed some versions of helm and ran `scripts/create_release_pr -v 2.0.8`.
We ran the usual commands to create Pelorus Operator files
```
podman login ...
oc login ...
rm -rf pelorus-operator && mkdir pelorus-operator && scripts/create_pelorus_operator
cd pelorus-operator
make podman-build
make bundle-build
make podman-push
make bundle-push
```
(Note: sent the images to my personal account to test them before sending to production, …
> release: Pelorus Operator version 0.0.5

- docs/GettingStarted/configuration/ExporterWebhook.md
- exporters/webhook/app.py
All other exporters can read the metrics from other endpoints in the URL route such as / or /metrics as well as /whatever
To make it consistent webhook exporter also presents the prometheus metrics on the GET event for all endpoints.
For the POST events only /pelorus/webhook can be used.
Disallow all other methods.
Fixes #889
Fixes #888 
It's enough to run the exporter via python and test endpoints:
```
$ python exporters/webhook/app.py
```
> Webhook exporter metrics route to be same as other exporters

- CODE_OF_CONDUCT.md
Adapted from the Contributor Covenant a version 2.1 of the Code of Conduct for the Pelorus project.
> Add Code of Conduct for the Pelorus project.

- scripts/run-pelorus-e2e-tests
Add PagerDuty to end to end (e2e) script.
related to #880
To run end to end tests with PagerDuty, run
```
export REPO_NAME=pelorus
export PULL_NUMBER=911
export PAGER_DUTY_TOKEN=YOUR_TOKEN
./scripts/run-pelorus-e2e-tests -o mateusoliveira43 -b feat/pagerduty-test -e pagerduty_failure
```
To clean the environment afterwards, run
```
curl https://raw.githubusercontent.com/konveyor/mig-demo-apps/master/apps/todolist-mongo-go/mongo-persistent.yaml | oc delete -f -
helm uninstall pelorus --namespace pelorus
helm uninstall operators --namespace pelorus
```
> fix: add PagerDuty e2e test

- docs/Development.md
- docs/GettingStarted/configuration/ExporterCommittime.md
- exporters/committime/__init__.py
- exporters/committime/app.py
- exporters/committime/collector_azure_devops.py
- exporters/committime/collector_base.py
- exporters/failure/app.py
- exporters/requirements.txt
- exporters/tests/__init__.py
- exporters/tests/test_committime_exporter_app.py
- exporters/tests/test_exporters.py
- exporters/tests/test_failure_exporter.py
- exporters/tests/test_failure_exporter_app.py
- scripts/run-pelorus-e2e-tests
Fixes Azure devops URL parser.
resolves #898
resolves #902
related to #899 
Use committime with data comming from `https://dev.azure.com/{organization}/{project}/_git/{repository}` (or custom enterprise URL, instead of  `dev.azure.com`) and using [`GIT_API`](https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ExporterCommittime/#git_api) as `dev.azure.com` or `dev.azure.com/{organization}`.
To run e2e tests, run
```
./scripts/run-pelorus-e2e-tests -o mateusoliveira43 -b feat/azure-devops-test -e azure-devops-committime
```
To create test application, run
```
oc create namespace test-azure
oc create secret generic test-azure-secret --from-literal=password=YOUR_PERSONAL_ACCESS_TOKEN --type=kubernetes.io/basic-auth -n test-azure
oc secrets link builder test-azure-secret -n …
```
> fix: Azure devops URL parser

- exporters/tests/test_failure_exporter.py
Fix Jira integration test.
In the past weeks, Jira API was not consistent, giving different messages for using wrong password authentication. Because of this, I am removing the check of the error message from the test (but still testing with a error occurs).
resolves #902
Run `make integration-tests`.
> fix: Jira integration test

- .github/workflow_templates/build_push_exporters/action.yml
- .github/workflows/build-pelorus.yml
This allows to set proper tags whenever our chart points to a new tag.
The change moves some common action code to a template making less code duplication.
> Build exporter images with the tag from updated _imagestream_from_image

- Makefile
- docs/Development.md
- docs/UpstreamSupport.md
- exporters/tests/test_failure_exporter_app.py
- exporters/tests/test_failure_exporter_pager_duty.py
- scripts/run-pelorus-e2e-tests
Fix PagerDuty end to end (e2e) tests.
resolves #880
To run end to end tests with PagerDuty, run
```
export PAGER_DUTY_TOKEN=YOUR_TOKEN
./scripts/run-pelorus-e2e-tests -e pagerduty_failure
```
To clean the environment afterwards, run
```
curl https://raw.githubusercontent.com/konveyor/mig-demo-apps/master/apps/todolist-mongo-go/mongo-persistent.yaml | oc delete -f -
helm uninstall pelorus --namespace pelorus
helm uninstall operators --namespace pelorus
```
> fix: PagerDuty e2e test

- docs/GettingStarted/configuration/ExporterWebhook.md
- exporters/tests/test_pelorus_webhook.py
- exporters/tests/test_pelorus_webhook_handler.py
- exporters/webhook/app.py
- exporters/webhook/models/pelorus_webhook.py
- exporters/webhook/plugins/pelorus_handler.py
- exporters/webhook/plugins/pelorus_handler_base.py
Adds option to configure webhook exporter to share SECRET_TOKEN to validate payload integrity.
With the webhook configured to use SECRET_TOKEN the sender is obligated to calculate the SHA256 hash of the payload and include that hash as a header during POST method, otherwise the payload will not be received and recorded by the webhook.
resolves #922 
1. Deploy Pelorus with the webhook exporter that does have SECRET_TOKEN configured
2. Send sample data using curl to the webhook exporter endpoint as described in the examples section of the documentation
Alternatively use python to start the webhook exporter previously exporting SECRET_TOKEN:
```shell
$ make dev-env
$ source .venv/bin/activate
$ export SECRET_TOKEN="My Secret Token"
$ python exporters/webhook/app.py
```
And sent from another …
> Add secret to secure payload for the webhook exporter

- exporters/requirements.txt
Pinning azure-devops is required to ensure it properly loads it's internal git client module.
Fixes: #949
> Pin azure-devops dependency due to it's new version issue

- .github/pull_request_template.md
No.
After #940, a new PR template was added, but GitHub does not show the templates options when user creates an PR through the UI.
After merging, the user can choose a PR template through `.github/pull_request_template.md`.
> fix: Choose PR template from UI

- docs/GettingStarted/configuration/ExporterDeploytime.md
- docs/GettingStarted/configuration/ExporterWebhook.md
- exporters/deploytime/app.py
- exporters/pelorus/timeutil.py
- exporters/tests/data/webhook_pelorus_committime.json
- exporters/tests/data/webhook_pelorus_deploytime.json
- exporters/tests/data/webhook_pelorus_failure_created.json
- exporters/tests/data/webhook_pelorus_failure_resolved.json
- exporters/tests/test_datetime.py
- exporters/tests/test_in_memory_metric.py
- exporters/tests/test_pelorus_base_plugin.py
- exporters/tests/test_pelorus_webhook.py
- exporters/tests/test_pelorus_webhook_handler.py
- exporters/tests/test_webhook_models.py
- exporters/webhook/README.md
- exporters/webhook/app.py
- exporters/webhook/models/pelorus_webhook.py
- exporters/webhook/plugins/pelorus_handler.py
Make deploytime exporter consistent between webhook and deploy type exporter.
Current exposed [metric](https://github.com/dora-metrics/pelorus/blob/616ff8f4ebbd807038e93de15e5f8c14da7c4b2e/exporters/webhook/app.py#L124-L126) format of the webhook's deploytime is different from the original deploytime exporter [metric](https://github.com/dora-metrics/pelorus/blob/616ff8f4ebbd807038e93de15e5f8c14da7c4b2e/exporters/deploytime/app.py#L55-L59).
The difference is visible below and shows that the webhook exporter implementation does not add timestamp() to the metric. 
There are few reasons why *not* to include the timestamp within the metric as discussed under https://github.com/dora-metrics/pelorus/discussions/956, however with current queries and Prometheus limitations we are required to use …
> Ensure deploytime exporter accepts only valid timestamps

- .github/workflow_templates/build_push_exporters/action.yml
- .github/workflow_templates/comment-pr/Dockerfile
- .github/workflow_templates/comment-pr/action.yml
- .github/workflow_templates/comment-pr/main.py
- .github/workflows/test-images.yml
- .github/workflows/trigger-test-images.yml
- docs/Development.md
- docs/requirements.txt
Create test images for each PR, making testing of operator easier for the developers.
resolves #881
depends on #969
Test images available! 🧪🚀 To test operator with them, run
```
operator-sdk run bundle \
quay.io/pelorus/rc-pelorus-operator-bundle:vpr948-abc555 \
--namespace test-pelorus-operator
```
To clean up environment afterwards, run
```
operator-sdk cleanup pelorus-operator --namespace test-pelorus-operator
```
> Feat: Create test images for PRs

- .github/workflow_templates/comment-pr/main.py
related to #881
Fix pydantic attribute name (so it can read what GitHub actions send to it).
Check following PR.
> fix: Custom action pydantic attribute name

- .github/workflows/chart-lint.yml
- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- docs/GettingStarted/Overview.md
- docs/GettingStarted/configuration/ExporterFailure.md
- docs/UpstreamSupport.md
- exporters/failure/app.py
- exporters/failure/collector_azure_devops.py
- exporters/pelorus/timeutil.py
- exporters/tests/test_failure_exporter_app.py
- exporters/tests/test_failure_exporter_azure_devops.py
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- scripts/run-pelorus-e2e-tests.sh
Add Pelorus support for [Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards?view=azure-devops) (Azure DevOps issue tracker). About Azure Boards:
- An issue is called **work item** in it
- work items allows adding **tags**, which can work as labels
- work items have 3 states: **To Do**, **Doing** and **Done**. It is considered resolved when it status changes to Done
- For filtering, in addition to tags, we can use **type** (by default, task, issue or epic, but I think user can create custom ones) and priority (1, 2, 3 or 4). Also, projects can be used
- For further filtering, reason, boards and sprints could be used perhaps, but seems too much. Also, `Microsoft.VSTS.Common.Severity` and `Microsoft.VSTS.Common.Risk` were considered, but were …
> feat: Azure Boards (Azure DevOps issue tracker) support

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- docs/Development.md
- exporters/deploytime/app.py
- exporters/provider_common/openshift.py
- exporters/tests/openshift_mocks.py
- exporters/tests/test_commons_openshift.py
- exporters/tests/test_deploytime.py
- exporters/webhook/store/in_memory_metric.py
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
Rework of deploytime codebase
Move functions to the common openshift library.
Optimize querying for the parent objects such as ReplicaSet and ReplicationController. With this implementation we relay on known api versions and api objects directly from the pod.
Added cache to optimize queries to the OpenShift API for the parent objects. For the running pods we do want to always have the latest state, which means we can't do caching there.
Reworked extracting image SHAs from the running pod instances, which is a base for the skopeo as we also get the full URI of the image.
> Rework of deploytime codebase

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- docs/GettingStarted/configuration/ExporterFailure.md
- exporters/failure/collector_jira.py
- exporters/tests/test_failure_exporter.py
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
resolves #994
Add fallback option when Pelorus can not determine `app_name` from issue.
Create Pelorus failure exporter using
```yaml
apiVersion: charts.pelorus.dora-metrics.io/v1alpha1
kind: Pelorus
metadata:
name: test-app-name-option
spec:
exporters:
instances:
- app_name: failure-exporter
exporter_type: failure
extraEnv:
- name: API_USER
value: jira_user
- name: TOKEN
value: jira_token
- name: SERVER
value: https://pelorustest.atlassian.net
- name: APP_NAME
value: robotron
- name: PROJECTS
value: 'Test,pelorus_tekton_test,todolist-mongo'
- name: JIRA_RESOLVED_STATUS
value: DONE
```
and check that no issues are related to app "unknown" and app "robotron" appears in Grafana, using Operator commented by CI.
> feat: Add fallback option when Jira exporter can not determine application

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- charts/pelorus/templates/prometheus-rules.yaml
- docs/GettingStarted/configuration/ExporterFailure.md
- docs/GettingStarted/configuration/ExporterWebhook.md
- exporters/failure/collector_base.py
- exporters/webhook/app.py
- exporters/webhook/models/pelorus_webhook.py
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/helm-charts/pelorus/templates/prometheus-rules.yaml
Adding Timestamp to the Failure exporter is important to properly calculate Change Failure Rate Over Time (CFR)
The CFR metric is a simple number that represents the number of failed deployments to the number of all deployments. As such without the timestamp we were adding the Failures to the previously known ones and never calculating properly based on a chosen time window.
The max_over_time is required to be able to deduct creation time of the failure from the resolution time of that failure to properly calculate Mean Time to Restore and other metrics. Without that we would almost never had the time window that both metrics create/failure would be within it and as such the deduction would return nothing.
resolves #1010
Use script provided in the #1010 to test the scenario.
> Add Timestamp to the Failure exporter

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- docs/GettingStarted/configuration/ExporterCommittime.md
- exporters/committime/app.py
- exporters/committime/collector_base.py
- exporters/committime/collector_containerimage.py
- exporters/provider_common/openshift.py
- exporters/tests/data/skopeo_custom_container_labels.json
- exporters/tests/data/skopeo_default_container_labels.json
- exporters/tests/data/skopeo_malformed_json_file.json
- exporters/tests/data/skopeo_missing_container_labels.json
- exporters/tests/httpd_docker_with_labels/Dockerfile
- exporters/tests/test_committime_exporter_containerimage.py
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
resolves #967
A new type of provider for the commit time exporter that works similarly to the deploytime, but additionally for the found running applications it reaches out to the external container registry and tries to get commit time from the Docker label.
Currently run the exporter using python interpreter on the system that has skopeo installed:
```
$ export KUBECONFIG=<path to kubeconfig>
$ export LOG_LEVEL=debug
$ export PROVIDER=containerimage
$ export NAMESPACES=<optional step to list namespaces for running pods>
$ python exporters/committime/app.py
$ #Open http://localhost:8080
```
This exporter can be use to calculate the above commit time, based on the provided example application, that is already in the test quay.io repository:
Create ReplicaSet using OCP WebUI or `oc apply` …
> Skopeo exporter

- _test/prometheus/test.yaml
- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- charts/pelorus/templates/dashboard-sdp-byapp.yaml
- charts/pelorus/templates/dashboard-sdp.yaml
- charts/pelorus/templates/prometheus-rules.yaml
- docs/GettingStarted/configuration/PelorusExporters.md
- exporters/committime/collector_base.py
- exporters/deploytime/app.py
- exporters/failure/collector_base.py
- exporters/provider_common/__init__.py
- exporters/tests/test_in_memory_metric.py
- exporters/webhook/store/in_memory_metric.py
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/helm-charts/pelorus/templates/dashboard-sdp-byapp.yaml
- pelorus-operator/helm-charts/pelorus/templates/dashboard-sdp.yaml
- pelorus-operator/helm-charts/pelorus/templates/prometheus-rules.yaml
resolves #964
Add hierarchy filter in Grafana dashboard `by_app`.
Create Pelorus instance with
```yaml
kind: Pelorus
apiVersion: charts.pelorus.dora-metrics.io/v1alpha1
metadata:
name: test-hierarchy-filter
namespace: test-pelorus-operator
spec:
exporters:
global: {}
instances:
- app_name: webhook-exporter
exporter_type: webhook
```
and run this script with the webhook endpoint
```python
import argparse
import json
import time
from urllib import request
if __name__ == "__main__":
parser = argparse.ArgumentParser()
parser.add_argument("url", type=str)
arguments = parser.parse_args()
current_timestamp = int(time.time())
for index, app in enumerate(
[
"group/subgroup/application_{index},class/application_{index}",
"group/subgroup/application_{index}", …
```
> feat: Add app hierarchy filter in Grafana

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- docs/Development.md
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
related to #1007
Release for version 0.0.7 of Pelorus Operator (and 2.0.10 of repo).
To test the release candidate, run the command the CI posted in this PR.
Also, read, review and update [release body](https://github.com/dora-metrics/pelorus/releases) marked as drafted.
> release: Pelorus Operator version 0.0.7

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- charts/pelorus/templates/prometheus-scrape-config-secret.yaml
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/helm-charts/pelorus/templates/prometheus-scrape-config-secret.yaml
When passing a list to `federate_openshift_monitoring.metrics_filter` that contains more than one node, every node after the first gets rendered in the helm chart, is missing indentation.
Example:
Given the following values file:
```
federate_openshift_monitoring:
enabled: true
metrics_filter:
- "kube_pod_container_info{}"
- "kube_pod_status_phase{}"
exporters:
global: {}
instances: []
```
You get the following output:
```
helm template pelorus ./charts/pelorus/ --values examples/ocp-fed-values.yaml --debug | yq '. | select(.kind == "Secret" and .metadata.name == "pelorus-prometheus-additional-scrape-configs")' | jq -r '.data["prometheus-additional.yml"]' | base64 -d
install.go:159: [debug] Original chart version: ""
install.go:176: …
```
> fix: federate_openshift_monitoring breaks with multiple metrics filters

- README.md
- docs/UpstreamSupport.md
- scripts/check_openshift_version.py
The PROW CI jobs were updated to use only latest OCP release for their runs. The documentation and the check openshift version script needs to be changed as well.
PROW PR: https://github.com/openshift/release/pull/44348
> Update OCP check script and upstream support with the prow changes

- .github/workflows/shellcheck.yml
- Makefile
- scripts/get_tool_dl_url.py
- scripts/install_dev_tools.sh
Fixes #518
Fixes non-reported(?) issues with installing noobaa and shellcheck on ARM macs
It also looks like our shellcheck github action has been broken for a _while_. This PR:
- fixes the shellcheck makefile target
- simplifies that target
- makes shellcheck linting mandatory (I can separate this into another PR if you wish.)
- makes the github action only run on one version of python (it's irrelevant to python)
1. Remove all non-python executables from your venv's `bin` dir (or just remove the whole venv)
2. `make cli_dev_tools`
3. Verify that all expected cli tools are present, including shellcheck and noobaa  
(this only matters if you're on an ARM mac)
1. Modify one of the tools' repo names / URLs in `get_tool_dl_url.py` so that the url check fails
2. Verify that the …
> Fix various dev tool install issues, make shellcheck a required lint

- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/Dockerfile
- pelorus-operator/Makefile
- pelorus-operator/bundle.Dockerfile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/bundle/metadata/annotations.yaml
- pelorus-operator/bundle/tests/scorecard/config.yaml
- pelorus-operator/config/default/manager_auth_proxy_patch.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/config/scorecard/patches/basic.config.yaml
- pelorus-operator/config/scorecard/patches/olm.config.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- scripts/pelorus-operator-patches/05_remove_auth_proxy_container.diff
Updated operator with new operator-sdk version 1.33.
> Regenerated pelorus-operator with new operator-sdk version

- _test/prometheus/test.yaml
- charts/operators/Chart.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- charts/pelorus/templates/prometheus-rules.yaml
- exporters/committime/__init__.py
- exporters/committime/collector_azure_devops.py
- exporters/committime/collector_base.py
- exporters/committime/collector_bitbucket.py
- exporters/committime/collector_containerimage.py
- exporters/committime/collector_gitea.py
- exporters/committime/collector_github.py
- exporters/committime/collector_gitlab.py
- exporters/tests/integration/test_committime.py
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/helm-charts/pelorus/templates/prometheus-rules.yaml
- pelorus.code-workspace
resolves #1089 
This change adds a new `repo_url` label to the committime metric across all providers. It ensures that when we capture a commit time, we also capture the source code repo URL for that commit. This will help us to show users where their metrics are coming from and help users validate the metrics we collect when there are questions about how we're getting our data.
Deploy the operator from the PR builds above.
Set up a pelorus instance with the following comittime exporter types:
```
- enabled: true
app_name: committime-image
exporter_type: committime
extraEnv:
- name: PROVIDER
value: containerimage
- enabled: true
app_name: committime-git
exporter_type: committime
extraEnv:
- name: PROVIDER
value: git
```
Generate data by running through the examples here: …
> Include repo url in committime

- charts/operators/Chart.yaml
- charts/operators/templates/grafana-subscription.yaml
- charts/operators/values.yaml
- charts/pelorus/Chart.lock
- charts/pelorus/Chart.yaml
- charts/pelorus/charts/exporters/Chart.yaml
- charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- charts/pelorus/templates/prometheus-service.yaml
- pelorus-operator/Makefile
- pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/bundle/metadata/properties.yaml
- pelorus-operator/config/manager/kustomization.yaml
- pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
- pelorus-operator/config/rbac/role.yaml
- pelorus-operator/helm-charts/pelorus/Chart.lock
- pelorus-operator/helm-charts/pelorus/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
- pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
- pelorus-operator/helm-charts/pelorus/templates/prometheus-service.yaml
- scripts/pelorus-operator-patches/bundle-patches/01_prometheus_grafana_dependencies.diff
resolves #1156 
This change upgrades the prometheus and grafana operator dependencies to the latest versions currently available in OperatorHub:
* Prometheus Operator v4.10.0
* Grafana Operator v5.12.0
1. Deploy PR build of the operator, make sure install goes well. 
2. Need to find some way to test upgrades in an instance that contains data
> Upgrade grafana and prometheus versions to latest available

- README.md
We accidentally overwrote our README with the readme from the CT repo on a recent PR. This change puts it back.
look at readme.
> Restore readme that got accidentally replaced by a recent change
